app/index.html, app/scripts/bootstrap.js, app/scripts/controllers/main.js
these update support view it via http://domain.com/editor/ and http://domain.com/editor/index.html; but it can't be visited by  http://domain.com/editor;
my nginx config is like blow:
```nginx
location /editor {
proxy_pass http://localhost:9000/;
}
```
=> #321 support deploy to subfolder or reverse proxy via nginx

app/scripts/controllers/preview.js, app/scripts/services/auth-manager.js, test/e2e/specs/5_session_auth_test.js
fix #311 
> fix it by create a hash key to map the security property with security options
=> [security] retain the authentication

app/scripts/directives/tryoperation.js, app/templates/try-operation.html
After checking for an existing security property in the operation, it also checks now for the existence of the root level security object and use it as fallback if needed. This way it still allows the operation to overwrite the root with just an empty array, 
This fixes Issue #302 but not #318.
=> Fix for #302: tryoutoperation falls now back to root security object

app/config/defaults.json
No obvious reason to bifurcate the analytics, so switching to the original ID.
=> Move to a single tracker for swagger

README.md
GitHub recommends changing to https. See GitHub FAQ "Which remote URL should I use?" at https://help.github.com/articles/which-remote-url-should-i-use/
(My particular need for this is because I password protect ssh git credentials, which means GitHub prompts me for a password when I clone using ssh git instead of HTTPS; it is very helpful for scripted installations to have HTTPS, because there's no need for a password prompt)
=> Update git clone URL to https

grunt/connect.js
In my environment, other development server uses port 9000. It's useful to change the port with env var.
=> Use PORT environmental variable for serve task

Dockerfile, grunt/connect.js
Disable livereload for dist goal as this is not necessary when deploying the application outside of developments, and can lead to timeouts of the livereload request in production(interface *will take a few minutes to show up).
Also Docker command executed would always build at runtime, which is can be done earlier at docker build time, hence speeding up the container starting time.
=> Disable grunt livereload for dist goal and speed container start time

app/templates/security.html
security.html has duplicate Authorization URL titles, the second one is supposed to be Token URL.
=> Correct 'Authorization' to 'Token' URL

bower.json
I had problems getting the swagger-editor to run after a recent rebuild of my Docker container.
This is the issue I was getting:
Updating to sway-worker 1.8.0 fixed it apparently.
=> Update sway-worker to 1.8.0

app/scripts/directives/operation.js, app/styles/components/operation.less, app/templates/operation.html
Renders response examples. This also fixes an error in
documentations for `hasAResponseWithSchema` and
`hasAResponseWithHeaders`.
Fixes https://github.com/swagger-api/swagger-editor/issues/674
Fixes https://github.com/swagger-api/swagger-editor/issues/698
Fixes https://github.com/swagger-api/swagger-editor/issues/652
=> [preview] Render response examples

app/scripts/services/fileloader.js
In load method do not convert to json and back to yaml if it
is already a yaml.
Fix https://github.com/swagger-api/swagger-editor/issues/697.
=> [fileloader] Import a yaml file

app/templates/operation.html
Found that response headers was never shown, because the ng-if was checking for "response.header.length > 0", which will never be true, as "response.header" is an object (map-like) and not and array.
=> Response headers was never shown

app/scripts/directives/tryoperation.js
Proposition for solving issue #684
What was the problem? When a query parameter (let's say `foo`) was defined as an optional string, it would show up nevertheless in the url (e.g. `/route?foo=&bar=stuff`)
The cause was in the following piece of code being totally irrelevant in the `hashifyParams` function in `tryoperations.js`
```js
// if this parameter is not provided (empty string value) by user and it's
// not required, move to next parameter without adding this one to the hash
if (param.type === 'string' && paramValue === '' && !required) {
return hash;
}
```
because for some reason the parameter's value becomes `undefined`.
As I could not figure out the reason why this would happen, and given my limited knowledge, I just went for this quick-and-dirty fix: just adding a check for the …
=> Fixing issue #684

app/scripts/controllers/paste-json.js, app/scripts/services/builder.js
Fixes https://github.com/swagger-api/swagger-editor/issues/805
Remove the code in builder.js due to fixation of the bug.
=> [import] Use the new Sway-worker api signiture in paste JSON

index.js, package.json
Partially fixes issue: https://github.com/swagger-api/swagger-editor/issues/874
This fix is partial because although it fixes the Promise dependency, there is still an issue with IE 9. IE 9 does not support WebWorkers, which this app appears to depend on.
Fixes IE10 and IE 11
=> Added polyfill for Promise to support < IE11

scripts/services/ast-manager.js
=> Add another base case to a AST Manager recursive function

docs/cors.md
The existing example will not work in 48 and newer versions of chrome. Disable-web-security also requires user-data-dir parameter in order to work in chrome 48+.
See [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=575690). It is safe to ignore the no value comment for user-data-dir, it has since been given a [default value](https://www.chromium.org/user-experience/user-data-directory).
=> Update for Chrome 48+

scripts/directives/operation.js, templates/operation.html
=> Do not show description column when there is no description.

styles/components/modal.less
Before:
After:
Signed-off-by: Thanasis Katsadas <thanasis00@gmail.com>
Signed-off-by: Dionysis Grigoropoulos <dgrig@erethon.com>
=> Fix overflow error message inside modal on Firefox

templates/operation.html
I have added rendering for the externalDocs property for operations in the same way as it is rendered for the specs-info area.
=> Added externalDocs rendering for operations

config/defaults.json, config/defaults.json.guide.js
Right now, when serving swagger-editor on a secure host, the communication to http://generater.swagger.io is blocked in all or most browsers due to it being flagged as insecure content. 
Making these links protocol agnostic makes sure that they will be using https:// whenever swagger-editor is also being accessed over https://
=> Make generator.swagger.io links protocol agnostic

scripts/controllers/tryoperation.js
Multipart/formdata requests did not include `type !== file` parameters. This addresses that.
Please review, @saharj 
=> Allow multipart/formdata to include non-file parameters

make-webpack-config.js, webpack-hot-dev-server.config.js
@shockey 
This uses the `dist-bundle` as the base config, for hot-webpack.
This fixes the issue of `npm run dev` not working.
=> Fix the dev build, to use the dist-bundle as an entry point

src/plugins/validation/semantic-validators/validators/items-required-for-array-objects.js, src/plugins/validation/semantic-validators/validators/parameters.js, test/plugins/validation/semantic/items-required-for-array-objects.js, test/plugins/validation/semantic/parameters.js
Fixes #1239.
This only adds the validation for parameters, as it already exists for any object whose name is `schema` or parent's name is `definitions`.
@webron, asking you to review. I looked through the specification for any instances of `type: array` and it looks like we're covering it all, but want to be sure.
=> Add type: array validation for parameters

test/plugins/validation/semantic/paths.js
Protects against #1276 in 3.x.
=> Add test to prevent regression from 2.x path templating errors issue

.babelrc, package.json, src/plugins/editor-autosuggest-keywords/keyword-map.js, src/plugins/validation/validation.worker.js, src/polyfills.js, webpack-dist-bundle.config.js, webpack-dist.config.js, webpack-hot-dev-server.config.js, webpack-standalone.config.js
Brings back our old friend.... IE11 compatibility 😄 
Changes:
- Adopted the `core-js` polyfill injection structure that UI uses already
- Pinned a secondary dependency `bowser` at version `1.6.1` to solve an issue with `react-split-pane`
- Modified `keyword-map.js` to fix an IE11 quirk with the rest operator
I don't feel _great_ about version pinning `bowser` since we don't use it in our codebase, but it fixes the IE11 with no fuss.
=> IE11 fixes

src/plugins/validation/helpers.js
EZ.
Fixes this error:
```js
helpers.js:38 TypeError: Cannot read property 'set' of null
at eval (swagger-ui.js:5290)
at eval (swagger-ui.js:13214)
at eval (combineReducers.js:37)
at Array.forEach (<anonymous>)
at eval (combineReducers.js:34)
at Map.withMutations (immutable.js:1355)
at eval (combineReducers.js:33)
at computeNextEntry (<anonymous>:2:27469)
at recomputeStates (<anonymous>:2:27769)
at <anonymous>:2:31382
```
=> Fix startup error in Editor

src/plugins/validation/semantic-validators/validators/paths.js, test/plugins/validation/semantic/paths.js
Fixes https://github.com/swagger-api/swagger-editor/issues/1303 (added by @shockey)
Adds support for partial templates (e.g. '\api\Reports({id})' as opposed to '\api\Reports\id' ).
required for url paths following the OData conventions
=> Removes path validation blocking the usage of partial path templating.

swagger-editor-dist-package/deploy.sh
This PR:
- adds `index.html` to `swagger-editor-dist`
- makes `deploy.sh` `sed` commands valid in both Linux and macOS/BSD `sed` flavors
- updates `deploy.sh` comments for clarity
CC: #1490
=> Update dist deploy script

src/plugins/validation/semantic-validators/validators/parameters.js
Fixes #1525.
This should cut down on cases of "mistaken identity" where `parameters` is used as a freely-named key (CC #1343).
=> Don't validate parameter `type` when there is no `in` value

src/plugins/editor-autosuggest/helpers.js
This PR uses the existing `wrapCompleters` interface to wrap our custom Ace completers in try/catch blocks.
This PR fixes* #1414 (hopefully). This bug has been hard to pin down, but I've been able to consistently reproduce the OP's issue. 
My approach here hinges on the root cause I surmised about in #1414:
> I have a theory: when our autosuggest code throws an uncaught error, Ace returns the current character as the resolved autosuggest value - so when live autocomplete fires and ends with an error, that buffer is appended to the value under the cursor, and the user sees a repeated character.
This PR sidesteps that failure mode by catching errors from within our autosuggest plugins, and cleanly feeding an empty result into Ace's completion callback.
I tested the live autosuggest …
=> Add try/catch to Ace autocompleters

src/standalone/topbar/topbar.jsx
This PR modifies JSON/YAML save functionality to name OpenAPI documents `openapi.[yaml|json]` instead of `swagger.[yaml|json]`.
Fixes #1566.
I tested downloading an OpenAPI and Swagger document, and everything was correct.
=> OpenAPI JSON/YAML download filenames

src/plugins/validation/semantic-validators/validators/walker.js, test/plugins/validation/semantic/walker.js
Adds a semantic validator for Swagger 2.0 $ref values.
(OAS 3.0 support has been added to https://github.com/swagger-api/swagger-editor/issues/1460).
Fixes #1560.
- New unit tests
- Manual testing
=> Add semantic validator for $ref values

src/plugins/validation/get-timestamp.js, src/plugins/validation/semantic-validators/hook.js, src/plugins/validation/semantic-validators/validators/index.js, src/plugins/validation/semantic-validators/validators/refs.js, src/plugins/validation/semantic-validators/validators/walker.js, test/plugins/validation/data/petstore-expanded.swagger.js, test/plugins/validation/semantic/index.js, test/plugins/validation/semantic/walker.js
- Fixes a corner case where $refs that reference an entire remote document would fail validation
- Adds an integration test set that ensures Petstore Expanded doesn't report any errors or warnings
- Fixes a mostly-unrelated issue with the $ref collector not being able to tabulate reference usage in JSON definitions
https://github.com/swagger-api/swagger-editor/pull/1570#issuecomment-346046947.
- I added four unit tests.
- I tested my changes manually within the Editor
=> $ref formatting validation with whole-document paths

package.json, src/layout.jsx, src/plugins/editor/components/editor-container.jsx, src/plugins/editor/components/editor.jsx, src/plugins/jump-to-path/components.jsx, src/standalone/standalone-layout.js, src/standalone/topbar/topbar.jsx
Add "prop-types" dependency to package.json. Update import statements throughout so that they explicitly get PropTypes from the prop-types package instead of the react package.
PropTypes has been removed from React-16. People wishing to use React-16 will have a bad time. Importing PropTypes through an explicit dependency instead of through react will solve this problem.
Build using npm run build and integrated into my project.
=> Use prop-types dependency for React-16 support

src/standalone/topbar/topbar.jsx
Fixes https://github.com/swagger-api/swagger-editor/issues/1583 - however, the fix is to not display the Generate menu anymore (for now). It does keep the whole Topbar from crashing though 😄 
There's a quirk in Edge's fetch API, which will require a change in Swagger-Client in order to get the menus back. I'll follow up with a ticket there.
=> Don't display Generate menus until we have generator data

src/plugins/validate/index.js
Don't run Swagger 2 validation on OAS 3.0 🤔 
Fixes swagger-api/swagger-editor#1600, fixes swagger-api/swagger-editor#1599.
Existing unit tests pass; manually tested as well.
- [] I have added tests to cover my changes.
=> Add global switching logic to disable semantic validation for OAS3

src/plugins/validate/validators/schema.js, test/plugins/validate/schema.js
Fixes #1601.
The new semantic error is still wedged between some nonsense schema errors, but that's a fight for another day.
=> Add semantic validator for "\Z" anchors in regex patterns

src/plugins/validate-semantic/validators/refs.js, test/plugins/validate-semantic/refs.js
- Modifies $ref sibling validator to report warnings instead of errors; adds tests to match change
- Adds test for unused definition $ref validator, which was previously lacking tests
https://github.com/swagger-api/swagger-editor/issues/1305, https://github.com/swagger-api/swagger-editor/pull/1306.
=> fix(semval): restore warning-level validators and add missing tests

src/index.js
cc: https://github.com/swagger-api/swagger-ui/issues/4105#issuecomment-357921922
=> improve: enable `showExtensions` option by default

src/standalone/topbar/topbar.jsx
Addresses regression reported in https://github.com/swagger-api/swagger-editor/issues/1648.
=> fix(topbar): provide `handleResponse` as a component method

src/plugins/validate-semantic/validators/refs.js, test/plugins/validate-semantic/refs.js
This PR uses Swagger-Client's upcoming `$$ref` meta patch fixes to validate $refs within a resolved spec.
Depends on https://github.com/swagger-api/swagger-js/pull/1237 being released.
Fixes #1560, again.
Test and control unit tests were added.
=> Validate $ref formatting via Swagger-Client $$ref meta patches

src/plugins/validate-semantic/selectors.js, test/plugins/selectors.js, test/plugins/validate-semantic/schema.js
The current spec sub-schema selector returns the children nodes of `additionalProperties` instead of the `additionalProperties` node itself. This is incorrect and causes potential validation bugs
Added new unit tests for the `allSchemas` selector
Fixes #1662
Added a whole bunch of unit tests for selectors
=> Fixed sub-schema selection for additionalProperties

src/plugins/validate-semantic/index.js, src/plugins/validate-semantic/selectors.js, src/plugins/validate-semantic/validators/oas3/refs.js, test/plugins/validate-semantic/oas3/refs.js
This PR adds a semantic validator that restricts the types of $ref values allowed in Request Body positions.
Fixes https://github.com/swagger-api/swagger-ui/issues/4164.
Test and control unit tests were added that check component, cross-operation, and remote references.
=> semantic validator for OAS3 request body $ref values

Dockerfile
I assumed the favicons were `.ico` files.... you know what they say happens when you assume.
=> `ico` -> `png`

package.json, src/plugins/validate-semantic/validators/2and3/refs.js, test/plugins/validate-semantic/2and3/refs.js
This PR adds a new semantic validator that ensures `$ref` values that are local pointers lead to a path that actually exists in the document.
This is needed since the new lazy resolution strategy led to the resolver not surfacing all pointer errors at all times.
Fixes #1700.
Unit tests have been added.
Caveat: once the path has been lazily resolved, a redundant Resolver Error may appear. I've chosen to not do anything about this for the time being, as it opens a small can of worms with regards to error filtering.
=> fix(semval): add $ref location existential validator

src/plugins/editor/components/editor.jsx
=> fix: don't fire new content into ReactAce if values are already reconciled

src/standalone/topbar/topbar.jsx
Fixes #1734, see the issue for more context 😄
=> never generate folded block scalars when converting URL-imported JSON to YAML

build-tools/deploy-docker-hub-tag.sh
Coordinating change for https://github.com/swagger-api/swagger-ui/pull/4567.
=> fix(docker-releases): trim leading `v` from image names

package.json, src/plugins/refs-util.js, src/plugins/validate-semantic/validators/2and3/refs.js, test/plugins/validate-semantic/2and3/refs.js
Fixes #871.
Depends on https://github.com/swagger-api/swagger-js/pull/1322.
1. Raise validation errors for unescaped values.
2. Silence validation errors for properly escaped values.
=> fix: properly validate $ref value escaping

docs/helpers.md, src/plugins/editor-metadata/index.js, test/plugins/editor-metadata/index.js
This PR adds a `getEditorMetadata` method to Swagger Editor, which provides:
- definition content as a string and object
- validation state as a boolean
- array of errors registered in state
Fixes #1590.
Five unit tests have been added 😄
=> feature: `getEditorMetadata` helper

src/plugins/validate-semantic/validators/2and3/refs.js, test/plugins/validate-semantic/2and3/refs.js
=> fix(semval): don't warn about Path Item $ref siblings

src/plugins/editor/editor-plugins/hook.js
Fixes a bug introduced in #1764 that was preventing editor plugins from running
cc: @ponelat
=> fix: restore casing of editor plugin names

package.json, src/plugins/ast/index.js, src/plugins/ast/jump-to-path.jsx, src/plugins/editor/editor-plugins/json-to-yaml.js, src/plugins/split-pane-mode/components/split-pane-mode.jsx, src/plugins/split-pane-mode/index.js, src/standalone/topbar/topbar.jsx, src/standalone/topbar/topbar.less
Compat branch for https://github.com/swagger-api/swagger-ui/pull/4713.
=> compat: move obsolete UI plugins to Editor

src/plugins/ast/ast.js, test/plugins/ast/ast-manager.js
=> compat(plugin:ast): adopt final Swagger UI implementation

src/plugins/editor-autosuggest-oas3-keywords/oas3-objects.js
Fixes #1863.
> It's _perfect_.
> 
> -- me, on OAS3 autocomplete, July 7, 2017
It was perfect except for this one part that wasn't 😄
=> fix(autosuggest): double-escape Responses digit regex mask

src/standalone/topbar/topbar.jsx, test/e2e/tests/.eslintrc, test/e2e/tests/bugs/1862.js
This PR forces the Topbar to rewrite `generator.swagger.io` URLs as HTTPS over port 443, which fixes mixed content security violations when using the Editor with swagger.io's Generator service over HTTPS.
Fixes #1862.
I added Cypress tests (and Cypress itself!).
=> fix: force HTTPS download session links for 2.0 io generator

src/index.js, src/standalone/styles/topbar.less, src/standalone/topbar/topbar.jsx, test/unit/plugins/validate-semantic/2and3/paths.js
This PR migrates Swagger Editor's Generate Menu implementation to the stable version of Generator 3, and drops the beta warning from our interface.
=> improvement: migrate to stable generator3 API

src/plugins/validate-semantic/validators/2and3/parameters.js, test/unit/plugins/validate-semantic/2and3/parameters.js
This PR modifies the `Sibling parameters must have unique name + in values` semantic validator to not take inherited (i.e., path-level) parameters into account when searching for duplicate name + in combinations.
This makes the validator more accurate (see OpenAPI Specification quote below) and its implementation more clear - everybody wins!
> `parameters`: a list of parameters that are applicable for this operation. If a parameter is already defined at the Path Item, the new definition will override it, but can never remove it. The list MUST NOT include duplicated parameters.
Fixes #1738.
Automated tests. Also tested against the [Bitbucket API](
https://bitbucket.org/api/swagger.json), and this snippet:
```yaml
swagger: "2.0"
info:
title: Simple test
description: Wow so simple
version: …
```
=> fix(validation): allow inherited parameters to overwrite without flagging as invalid

.dockerignore, Dockerfile, nginx.conf
The purpose is to reduce the loading time by reducing the amount of data transferred.
With a simulated 100 mbps internet connection :
* before :
* after :
`gzip_static` reduces the CPU used by nginx, by avoiding to gzip files for each request.
It reduces loading time by more than 1.5 second (and even more on a slow internet connection).
I compared network tab in Chrome Developer Tools with and without gzip.
=> Add gzip compression in nginx configuration to reduce file size

release/get-changelog.sh
I've been using a new style for release notes, this reflects that.
The new changelog generator now sorts items as we like them, and pulls in stray commits that may not be to the Angular convention's liking, but we may still want present.
=> housekeeping: make changelog generator more flexible

src/plugins/json-schema-validator/oas3-schema.yaml
this completes phase 1 of the Schema Validation Improvement Plan (the first half happened in #1982)
=> improvement: adopt @webron's OpenAPI 3.0 schema

package-lock.json, package.json, src/plugins/json-schema-validator/oas3-schema.yaml, src/plugins/json-schema-validator/swagger2-schema.yaml, src/plugins/json-schema-validator/validator/index.js, src/plugins/json-schema-validator/validator/jsonSchema.js, src/plugins/validate-semantic/validators/parameters.js, test/unit/plugins/json-schema-validator/index.js, test/unit/plugins/json-schema-validator/test-documents/1394.yaml, test/unit/plugins/json-schema-validator/test-documents/1480.yaml, test/unit/plugins/json-schema-validator/test-documents/1489.yaml, test/unit/plugins/json-schema-validator/test-documents/1511.yaml, test/unit/plugins/json-schema-validator/test-documents/1519.yaml, test/unit/plugins/json-schema-validator/test-documents/1672.yaml, test/unit/plugins/json-schema-validator/test-documents/1709.yaml, test/unit/plugins/json-schema-validator/test-documents/1711.yaml, test/unit/plugins/json-schema-validator/test-documents/1797.yaml, test/unit/plugins/json-schema-validator/test-documents/1808.yaml, test/unit/plugins/json-schema-validator/test-documents/1832.yaml, test/unit/plugins/json-schema-validator/test-documents/1853.yaml, test/unit/plugins/json-schema-validator/test-documents/parameter-exclusive-schema-content.yaml
This PR is the second phase of my schema validation improvement work (phase 1 was introduced via #1982 and #1984).
It includes changes to the OpenAPI validation schema documents, our AJV instance, and one small modification to our local JSON Schema meta-document.
A few techniques have been deployed here:
- migrating usage of `oneOf` to artificial `switch` constructs that pivot the validation schema based on specific keys
- most helpfully, using inline content schemas unless a `$ref` property is present
- providing custom, contextual error messages for assertion keywords within specific Objects
- flattening unnecessary constructs in the validation schemas
Notably, this modifies generated errors to report their locations with JSON Pointer-compliant strings. Downstream consumers of schema …
=> improvement: schema validation error quality (phase 2)

nginx.conf
This PR adds and removes some behaviors in the application server that makes Swagger Editor available within our Docker container.
Specifically...
They didn't serve any discernible purpose, since the server doesn't expose any useful API endpoints.
This header prevents Swagger Editor Docker deployments from being embedded via iframe (et al), which should prevent [clickjacking attacks](https://javascript.info/clickjacking).
While Swagger Editor isn't a particularly high-value target (or easily targetable via in a clickjacking scenario), we don't have a documented use case for iframes being useful -- let's close the door on this until/unless we do.
These issues were raised as part of a security audit - that's all I'm at liberty to say 😄 
None of the changes are high-impact w/r/t security, so …
=> housekeeping(docker): tighten application server security directives

src/plugins/validate-semantic/validators/2and3/refs.js, test/unit/plugins/validate-semantic/2and3/refs.js
Warning message updated, also changed tests for fixing this issue: https://github.com/swagger-api/swagger-editor/issues/2048. 
Update a simple warning message and tests.
Trying to fix the issue https://github.com/swagger-api/swagger-editor/issues/2048
Previous tests changed with new message.
=> 2048 - Sibling Ref - Message updated and tests added

src/plugins/validate-semantic/validators/2and3/paths.js, src/plugins/validate-semantic/validators/helpers.js, test/unit/plugins/validate-semantic/2and3/paths.js
2049 - New Validation added for parameters checking casing matches, test added.
New Validation Added for this ticket: Path parameter validation should be smart about improper casing #2049 
When parameters have the same characters but different casing scenarios compared with path elements you will be able to see this message: 
In this case we have a Petid parameter, and petid as path parameter.
Parameter names are case-sensitive. The parameter named Petid does not match the case used in the 
path /pets/{petId}.
This fixes the issue: https://github.com/swagger-api/swagger-editor/issues/2049
I added a test case in paths.js to validate this, and also did manual testing with swagger-editor tool.
=> 2049 - New Validation added for parameters checking casing matches.

package-lock.json, package.json, src/plugins/ast/ast.js, src/plugins/editor-autosuggest/fn.js, test/unit/plugins/editor-autosuggest/fn.js
This PR modifies `getPathForPosition`'s preparation logic to only insert a fake `- a: b` array member if the user's current line is empty (excluding the already-typed autosuggest prefix), which fixes some edge cases in which we were overzealously inserting array members within array member fragments, e.g.:
```yaml
myArray:
- one: "abc"
- two: 
```
...would previously be prepared to this invalid YAML:
```yaml
myArray:
- one: "abc"
- two: - a: b
```
...but with this change, will generate this valid prepared YAML instead:
```yaml
myArray:
- one: "abc"
- two: ~
```
---
In terms of testing:
* `getPathForPosition` unit tests have been added for ~all code branches, as well as~ the edge case in quesiton
* I've tested these changes manually using the Petstore definition
=> improve: `getPathForPosition` array member fragment preparation

LICENSE
Per the Apache Software Foundation guidelines for applying the Apache License 2.0:
https://www.apache.org/foundation/license-faq.html#Apply-My-Software
> You should include a copy of the Apache License, typically in a file called LICENSE, in your work, and consider also including a NOTICE file.
This will also help get swagger-editor properly listed on GitHub (and elsewhere) as Apache License 2.0 code instead of a custom license.
Cheers!
🎩
=> Use the full Apache License 2.0 text in LICENSE

src/plugins/validate-semantic/validators/2and3/schemas.js, test/unit/plugins/validate-semantic/2and3/schemas.js
Schema Object: enum values should conform to their schema's type
Error should appear at the enum item whose type doesn't match.
Added unit testing for all samples.
=> feat(validation): enum values should conform to their schema's type

src/plugins/local-storage/petstore.js, test/unit/plugins/json-schema-validator/test-documents/1511.yaml, test/unit/plugins/json-schema-validator/test-documents/1519.yaml, test/unit/plugins/json-schema-validator/test-documents/1853.yaml, test/unit/plugins/json-schema-validator/test-documents/response-schema-restrictions.yaml
I have replaced numeric keys in OpenAPI documents with strings, in accordance with the OpenAPI spec.
The OpenAPI spec requires that OpenAPI documents be expressable in JSON ([v2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#format) and [v3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#format)). YAML allows any type to be an object key, but OpenAPI does not. v3 has an explicit note to this effect in its Format section; it applies to v2 as well.
I think swagger-editor _should_ show an error when given YAML with non-string keys, but that doesn't look possible. The YAML parser (js-yaml) silently stringifies any object keys which are not strings, so swagger-editor's internals never see the integer keys. This is not the usual behavior of …
=> replace numeric keys in yaml files with strings

src/plugins/local-storage/index.js, src/plugins/validate-semantic/index.js
In `SemanticValidatorsPlugin.wrapActions.validateSpec`, it will fire 3 times on a page refresh:
"not-editor"
"local-storage" <-- Also new, I'm passing this text as an optional argument for easier debug
"editor"
Now, `validateSpec` will only subsequently call `debAll` function if "editor" case. Previously, validation was also occurring if "local-storage" case.
Fixes #1943
Also, YAML reduced to:
```
swagger: '2.0'
info:
title: test
version: 0.0.0
paths:
/pets:
get:
parameters:
- in: query
name: foo
type: string
enum: [apples, oranges]
default: bananas  # <---- should trigger error
responses:
200:
description: OK
```
Visual testing only
=> fix #1943 page refresh with local storage should validate only once

src/plugins/validate-semantic/selectors.js, test/unit/plugins/selectors.js
Previously, the `allDefinitions` selector only picked up global OAS2 schemas. This PR improves this selector to also pick up global OAS3 schemas in the `components/schemas` section.
**Note to reviewer:** Use the "[Hide whitespace changes](https://help.github.com/assets/images/help/pull_requests/diff-settings-menu.png)" option in the diff viewer to get a better idea of the changes in the tests.
Fix some (not all) of the scenarios mentioned in #2091.
Manually + added unit tests.
Before: Validation was NOT triggered for OAS3 schema components.
After: Validation is triggered for OAS3 schema components.
=> fix(validation): improve allDefinitions selector to pick up OAS3 schema components

src/plugins/validate-semantic/validators/helpers.js
During semantic validation, this line
https://github.com/ralphdoe/swagger-editor/blob/master/src/plugins/validate-semantic/validators/helpers.js#L42
tries to convert the parameter name to lower case. But if the parameter has no `name`, then `toLowerCase()` will raise an exception.
This PR attempts to fix the issue.
Fixes #2161.
Manually.
I don't know how to check this in unit tests.
n/a
=> fix: Prevent exception in checkForDefinition if parameter has no 'name'

test/e2e/tests/bugs/1862.js
Per [Cypress Docs](https://docs.cypress.io/guides/references/best-practices.html#Unnecessary-Waiting), replace "Unnecessary Waiting" for arbitrary time periods by using route aliases.
e.g. replace `cy.wait(100)` with `cy.wait(["@aliasname1", "@aliasname2"])`
Test bugs/1862 frequently fails on Jenkins CI
Updated test continues to pass on local (Mac, Node v13)
=> fix: wait for aliases in bugs/1862

src/plugins/validate-semantic/validators/2and3/refs.js
ref #2217
wrap the `pathFromPtr` call in a try/catch 
fixes #2217 
details: `pathFromPtr` from `json-refs` lib will throw new Error, instead of a resolved error message
* existing mocha tests continue to pass
* inbound migration to Jest-based tests will now pass.
=> fix(validation): use try/catch for pathFromPtr

src/standalone/topbar-insert/forms/components/InsertForm.jsx
Added `key` prop to each node that is added to the array, replaced the manual index tracker with the index that comes with Array.prototype.forEach().
React throwing error for missing key prop in array
Fixes #2222 
Error was only being thrown during Jest tests, tests no longer throw the error.
=> Fixes #2222

package-lock.json, package.json
bump `mini-css-extract-plugin` to v0.12.0
Note,  `mini-css-extract-plugin` v1.x and v2.x are breaking change for this project, and required additional webpack changes.
update dependencies
Local `npm run dev` continues to work. With the breaking versions (v1.x, v2.x), the `stylesheets.babel.js` is unable to compile.
current CI/CD does not catch breaking change in `stylesheets.babel.js`
=> chore(deps-dev): bump mini-css-extract-plugin to v0.12.0

webpack/_config-builder.js
* also fix linting (as required by husky)
Alongside url-loader@4 dependency bump in PR https://github.com/swagger-api/swagger-editor/pull/2343/, edit the baseRules set to treat /\.(png|jpg|jpeg|gif|svg)$/ as no esModule.
url-loader@3 changed the esModule default from false to true.
https://github.com/webpack-contrib/url-loader/releases/tag/v3.0.0
also fixed in swagger-ui: https://github.com/swagger-api/swagger-ui/pull/6861
browser
=> fix(webpack): assets should not be treaded as esModule

.github/workflows/dependabot-merge.yml, .github/workflows/nodejs.yml
For a Dependabot PR, new GA workflow to wait [6 minutes] to check if all other GA are successful. If yes, merge the Dependabot PR.
Replaces old "Merge Me" GA.
This security change disabled auto-merging:
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
=> ci(GA): allow dependabot to merge PRs (new GA)

package-lock.json
bump ua-parser-js from 0.7.1.18 to 0.7.28
update dependency, with security update
=> chore(deps): bump ua-parser-js from 0.7.1.18 to 0.7.28

src/plugins/validate-semantic/validators/2and3/schemas.js
This PR fixes an issue in semantic schema validators where the following (invalid) definition results in TypeError exceptions in the browser console.
```yaml
openapi: 3.0.0
info:
title: test
version: 1.0.0
paths: {}
components:
schemas:
test:
type: object
additionalProperties:   # note the missing subschema
```
Improve validators to gracefully handle missing/null schemas.
Tested manually to verify that the provided definition no longer causes console errors after this fix.
=> fix(validation): Gracefully handle null schemas in some validators

.github/workflows/nodejs.yml
* add cache node modules to artifact-bundle job
* set `env`
* add `cache cypress binary` to `build`
* add `cache node modules` to `artifact-bundle`
Missing Cypress binary in cache 
same implementation works in swagger-ui
=> chore(ga): add cache cypress binary

package-lock.json, package.json, src/plugins/editor/editor-plugins/json-to-yaml.js, src/plugins/json-schema-validator/index.js, src/standalone/topbar-insert/forms/components/AddForm.jsx, src/standalone/topbar-menu-file-import_file/components/ImportFileMenuItem.jsx, src/standalone/topbar/topbar.jsx, test/unit/plugins/json-schema-validator/index.js
Refs https://github.com/swagger-api/swagger-ui/pull/6804
We're using relatively old version of js-yaml. 4.x branch is a new one with huge amount of fixes.
=> feat(js-yaml): update our main YAML parser to v4.1.0

src/plugins/json-schema-validator/oas3-schema.yaml
These changes affects OAS 3.0.x JSON Schema and it's validation.
Refs #2762
=> fix(oas3): reply changes from canonical JSON Schema to our fork

src/plugins/validate-semantic/index.js, src/plugins/validate-semantic/validators/oas3/schemas.js, test/unit/plugins/validate-semantic/oas3/schemas.js
* New validation actions for OAS3 schemas. Specifically checks if both `readOnly` and `writeOnly` are present within `schemas.properties` and both set to true.
* New support tests to support OAS3 schemas validation actions
Fixes #2863 
New tests as noted above
=> fix(validation): OAS3 properties if readOnly, writeOnly both true

src/plugins/editor-autosuggest-oas3-keywords/oas3-objects.js
This PR fixes an incorrect regex that appears in the autocompletion popup under the `components.schemas` node. As explained in #2892:
> The character range `[.-_]` means "any symbol in Unicode table between `.` and `_`" (there are [50 characters](https://unicode-table.com/en/) in this range), whereas `[._-]` means these three characters only.
Fixes #2892.
=> fix: autocompletion regex for OAS3 component names

test/unit/plugins/validate-semantic/2and3/refs.js
Use `expect.arrayContaining()` to match against a subset of array items. Replaces `expect.objectContaining` check against each element by array position. 
Although these two tests have been running on CI for a long time, recently these tests started failing on my local Mac environment. The issue was that the resulting test array elements were not in the same order as expected in the test.
existing tests now pass again.
=> fix(jest): use more flexible matcher with `arrayContaining`

.github/workflows/deploy-rancher.yml
Per OP-16316
deploy-rancher.yml will now accurately reflect the Rancher K8s object name for editor-next
All relevant repository secrets have also been added.
=> ci changes for editor-next on rancher

.github/dependabot.yml, .github/workflows/dependabot-merge.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-rancher.yml, .github/workflows/nightly-build.yml, .github/workflows/release.yml, README.md
* apply github actions code changes from `master` branch to `next` branch
* update github package documentation reference
* Add warning documentation warning not to modify github actions workflows that reside in the `next` branch.
* Apply github actions code changes from `master` branch to `next` branch for reference.
* apply one github package documentation reference of `@swagger-api/swagger-ide` change to `@swagger-api/swagger-editor`
Clarity and reference for future development.
=> docs(ga): add do-not-modify warning to actions within `@next` branch

src/plugins/editor-preview-asyncapi/actions.js, src/plugins/editor-preview-asyncapi/components/AsyncAPIEditorPreviewPane.jsx, src/plugins/editor-preview-asyncapi/components/AsyncAPIValidationPane.jsx, src/plugins/editor-preview-asyncapi/components/AsyncApiPreviewValidationPane.jsx, src/plugins/editor-preview-asyncapi/components/AsyncApiPreviewValidationPane.test.js, src/plugins/editor-preview-asyncapi/components/_all.scss, src/plugins/editor-preview-asyncapi/components/_asyncapi.scss, src/plugins/editor-preview-asyncapi/index.js, src/plugins/editor-preview-asyncapi/reducers.js, src/plugins/editor-preview-asyncapi/selectors.js, src/styles/main.scss
`EditorPreviewPane` for AsyncAPI now contains its own separate ValidationPane. This new ValidationPane displays the results from the asyncapi/parser, and maintains the error message to user to fix the errors (while not rendering AsyncApi-React). 
The additional benefit is that `EditorPreviewPane` now displays more detailed error messages indicating why AsyncApi-React is unable to render.
`Jump to Marker` feature also works, matching the behavior of `EditorPane`'s `ValidationPane`, e.g. clicking on the error will cause the pointer to move to the appropriate line in `EditorPane`.
AsyncAPI definitions are first parsed by AsyncApi's own parser. If parsing fails, AsyncApi-React will be unable to render the definition. 
Current issues:
- parsing errors resulting from the `asyncpi/parser` has a …
=> feat: separate validationPane for asyncapi parser

package-lock.json, src/App.jsx
* CRA DefinePlugin to create `buildInfo` as a feature flag
* apply `buildInfo` to global window.versions object
Make build version info available in window.versions object. Feature match with legacy SwaggerEditor
local dev
=> feat: provide buildInfo to window.versions

package-lock.json, package.json, src/plugins/editor-monaco/utils/monaco-action-apidom-deref.js, src/plugins/editor-monaco/workers/apidom/ApiDOMWorker.js, src/plugins/editor-monaco/workers/apidom/adapters/SemanticTokensAdapter.js, src/plugins/topbar/actions/save-as-json-or-yaml/index.js
To maintain backward compatible behavior,
defaultLanguageContent context option for language
service has been introduced with following value:
```
defaultLanguageContent: {
namespace: 'asyncapi',
}
```
ApiDOM@0.31.0 comes with support for defaultLanguageContent
language service option.
Refs https://github.com/swagger-api/apidom/issues/1582
=> feat: skip validation for unrecognized specifications/formats

package.json, test/cypress/integration/monaco.spec.js, test/cypress/integration/plugin.validation-pane.spec.js
* Fix and re-enable Cypress `plugin.validation-pane.spec`. With the fix, parser should now always know to parse against the AsyncApi spec.
* Disable Cypress `monaco.spec`. ref #3184 
* Update `cypress open` command with `--e2e` flag. Since we do not currently use Cypress for component testing, this is a developer convenience, though still need to select the browser to use in Cypress UI.
* Improve Cypress reliability for `plugin.validation-pane.spec`
* Resolve CI errors since the Cypress@10 update
local cypress runs
=> fix(cypress): enable validation-pane and disable monaco spec

src/App.jsx, src/plugins/editor-content-jump-from-path-to-line/components/JumpFromPathToLine.jsx, src/plugins/editor-content-jump-from-path-to-line/components/jump-icon.svg, src/plugins/editor-content-jump-from-path-to-line/index.js, src/plugins/editor-content-jump-from-path-to-line/selectors.js, src/plugins/editor-monaco/actions.js, src/plugins/editor-monaco/components/MonacoEditor/MonacoEditor.jsx, src/plugins/editor-monaco/components/MonacoEditor/MonacoEditorContainer.jsx, src/plugins/editor-monaco/index.js, src/plugins/editor-monaco/reducers.js, src/plugins/editor-monaco/selectors.js, src/plugins/editor-monaco/utils/monaco-jump-from-path-to-line.js
* requires apidom-ls@0.36.0 or greater
* maps position from apidom-ls to monaco interface
* maintains legacy compatibility with `path` and `specPath` props
Re-integrate features from PR #3244. For details, refer to #3244.
Minor difference in this version here, in assigning `selectors.bestJumpPath` to `editor` statePlugin instead of the original `spec` statePlugin. This plugin otherwise had no direct interaction with SwaggerUI `spec` state or its selectors. 
Also some minor renaming changes.
Plugin was removed during the #3241, and now is re-integrated.
=> feat: jumpToPath plugin with Monaco

README.md, src/App.jsx, src/plugins/editor-content-type/actions.js, src/plugins/swagger-ui-adapter/index.js, src/plugins/swagger-ui-adapter/wrap-actions.js, src/plugins/swagger-ui-adapter/wrap-components/BaseLayout.jsx
SwaggerEditor comes with number of `preview` plugins that are responsible for rendering
the definition that's being created in the editor. These plugins include:
- **EditorPreviewAsyncAPIPlugin** - AsyncAPI specification rendering support
- **EditorPreviewAPIDesignSystemsPlugin** - API Design Systems rendering support
With a bit of adapting, we can use these plugins with SwaggerUI to provide ability
to render AsyncAPI or API Design Systems definitions with SwaggerUI.
```js
import React from 'react';
import ReactDOM from 'react-dom';
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';
import SwaggerEditor from '@swagger-api/swagger-editor';
const plugins = [
SwaggerEditor.plugins.EditorContentType,
SwaggerEditor.plugins.EditorPreviewAsyncAPI, …
```
=> feat: add ability to integrate preview plugins with SwaggerUI

package-lock.json, package.json, src/plugins/top-bar/actions/import-url.js
* Add `@braintree/sanitize-url@6.x`
* For `TopBar`'s `ImportUrl` method, sanitize user input of `url` before making a (axios) fetch request
* Handle error case if provided `url` is not a string, or is an empty string.
* In the event a fetch error occurs, the resulting error message also contains the sanitized url.
html safety. 
local
=> feat(topbar): sanitize importUrl input

src/plugins/top-bar/components/EditMenu/EditMenu.jsx, test/cypress/integration/plugin.top-bar.spec.js
Current fixtures are in JSON format. Select menu items should load and present these fixtures as YAML.
convert to YAML:
- OAS2.0
- OAS3.0
- OAS3.1
- AsyncAPI 2.4
leave as JSON:
- AsyncAPI 2.4 Petstore
- API Design Systems
It's easier for users to work in YAML. Also, this matches behavior from legacy SwaggerEditor
new Cypress tests. One for YAML, one for JSON
=> feat(topbar): load some fixtures as YAML

src/plugins/editor-preview-swagger-ui/components/EditorPreviewSwaggerUIFallback.jsx, src/plugins/editor-preview-swagger-ui/index.js, src/plugins/editor-preview-swagger-ui/wrap-components/EditorPreviewWrapper.jsx, src/plugins/layout/components/Layout/_layout.scss
Instead of rendering SwaggerUI's default "error" page, detect OAS3.1 and provide an internal fallback page with explanation.
Inform users that OAS3.1 rendering support with SwaggerUI is in the roadmap, but encourage editor use for OAS3.1
local, via Edit -> Load OpenAPI 3.1 fixture
=> feat: swagger-ui fallback page for oas3.1

src/plugins/editor-preview-swagger-ui/components/EditorPreviewSwaggerUIFallback.jsx
Fix nested <p> tag
console.error
=> fix: nested <p> in EditorPreviewSwaggerUIFallback

src/plugins/editor-content-type/actions.js, test/cypress/integration/plugin.top-bar.spec.js
* Fix the return values of the OAS30x/OAS31x matchers.
* Add Cypress tests for validation `contentType` detection of YAML/JSON
* Update Cypress tests for validating YAML conversion in Editor
fixes #3319
new Cypress tests
=> fix: `contentType` value returned by oas30x, oas31x YAMLMatch

src/plugins/top-bar/actions/import-url.js
Refs 8cfd2ac62af056e9a59fadc1f414a74d1dd7d56b
**Explanation**:
- sanitizer returns `about:blank` for any error so we can use that fact
- fix how data is passed to action creators
- always pass error object to error field of FSA
=> fix(top-bar): fix data handling in importUrl async thunk

src/plugins/top-bar/components/EditMenu/EditMenu.jsx, src/plugins/top-bar/components/EditMenu/EditMenuHandler.jsx
Refs ed614c521624604bcf747d146e2f9245ac42dead
Because the menu handlers were used, the effect was that editor content got dispatched twice to redux store: first time when the fixture got loaded and second time when fixture got converted and sent to editor as it's new content. 
This PR remedies the situation and uses async thunks directly in specific handlers to take care of conversion without reducing to redux store. Editor content is set only once.
Even more optimal solution exists and that is creating new selectors for YAML fixture. But IMHO this solution suffice.
=> refactor(edit-menu): convert format using async thunk

test/cypress/integration/plugin.top-bar.spec.js
Change `OAS2.0` and `OAS3.0` fixtures used by Cypress to use their respective Swagger Petsore version. No actual change to the fixtures themselves.
Use more long-term durable fixtures. Non Petstore fixtures are likely to be removed in the future.
local
=> refactor(test): e2e update choice of topbar fixtures

test/cypress/integration/plugin.editor-preview-api-design-systems.spec.js, test/cypress/integration/plugin.editor-preview-asyncapi.spec.js, test/cypress/integration/plugin.editor-preview-swaggerui.spec.js
New Cypress E2E tests that checks for expected content in the `EditorPreviewPane`.
Plugins:
* editor-preview-swagger-ui
* editor-preview-asyncapi
* editor-preview-api-design-systems
Fixtures:
* OAS2.0.x (Petstore)
* OAS3.0.x (Petstore)
* OAS3.1.x
* AsyncAPI 2.x (Streetlights)
* API Design Systems
BDD E2E tests for the `EditorPreviewPane`. The different plugins render different content.
all new tests
=> test(e2e): preview panes from plugins

test/cypress/integration/plugin.dialogs.spec.js
New Cypress E2E tests validating `cancel` operation and closing of a (confirm) dialog window. At the moment, only `TopBar` leverages the `Dialog` plugin, although future plugins and components are expected to use this plugin.
BDD E2E test coverage for Dialog boxes.
all new.
=> test(e2e): confirm dialog

test/cypress/integration/plugin.dialogs.spec.js, test/cypress/integration/plugin.dropzone.spec.js, test/cypress/integration/plugin.editor-monaco.spec.js, test/cypress/integration/plugin.editor-persistence.spec.js, test/cypress/integration/plugin.editor-preview-api-design-systems.spec.js, test/cypress/integration/plugin.editor-preview-asyncapi.spec.js, test/cypress/integration/plugin.editor-preview-swaggerui.spec.js, test/cypress/integration/plugin.editor-read-only.spec.js, test/cypress/integration/plugin.top-bar.spec.js, test/cypress/integration/plugin.validation-pane.spec.js, test/cypress/support/commands.js
* add Cypress command to intercept OAS2 and OAS3.0.x generator requests for list data
* Apply `cy.prepareOasGenerator()` to all Cypress tests, even if not currently actively making OAS2/OAS3 generator calls.
* Not included in this PR, intercepts to generator if user clicks on a generator menu item
Intercept/stub original http requests to OAS2/OAS3 generator lists, to avoid needing external http during CI.
locally, confirming external http calls for Swagger generator data is intercepted.
=> test(e2e): cy.Commands for `prepareOasGenerator` interceptors

.gitignore, test/cypress/integration/plugin.top-bar.spec.js, test/cypress/support/commands.js
* oas3.0.x mocks for the generator list and the generator download
* oas2.0 mocks for the generator list and the generator download
* `clearDownloadsFolder` cypress command
More comprehensive E2E tests for OAS2/OAS3.0.x generator lists. Cypress assertions can now "click" on a supported generator language where `http` requests are intercepted.
local Electron
local Chrome
=> test(e2e): oas2 and oas3 mock generator download

test/cypress/integration/plugin.dialogs.spec.js, test/cypress/integration/plugin.dropzone.spec.js
Add an assertion to close the `AlertDialog` component within the `Dropzone` E2E test. `AlertDialog` does not normally appear in "successful" workflows.
Indirect E2E test for plugin containing the `AlertDialog` component (close) interaction
local Electron
=> test(e2e): apply alertDialog assertion case in dropzone spec

test/cypress/integration/plugin.top-bar.spec.js
Import File and assert that content has changed.
Also update/correct several dev comments for other `Topbar` tests
BDD E2E test for Topbar -> File Menu -> Import File
local Electron
=> test(e2e): add assertion for Import File

test/cypress/integration/plugin.top-bar.spec.js, test/cypress/support/commands.js
Add stub for external converter http service. enables onClick of menu item
BDD E2E test for Topbar -> Edit Menu
local Electron
=> test(e2e): mock converter to oas3

NOTICE, package-lock.json, package.json, src/styles/_dropdown-menu.less, src/styles/main.less
Create `_dropdown-menu.less` from extracted stylesheet within the `react-dd-menu` library. Previously imported this stylesheet directly from the library package.
Update `NOTICE` to give proper credit to this extracted file.
Per npm author notice, `react-dd-menu` package has been deprecated. SwaggerEditor has only been using the package's stylesheet, which has been extracted in this PR.
local, no visual changes
=> chore(deps): extract stylesheet from deprecated react-dd-menu

src/plugins/editor-monaco/workers/apidom/apidom-mode.js
StandaloneServices is a singleton and can be initialized only once. Subsequent initializations are noops. This has a side effect which is inability to dispose of the services via StandaloneServices interface. Individual services can be disposed of separately, but if one decides to do that StandaloneServices will not able to initialize them again.
=> fix(monaco-editor): avoid disposal of standalone services

package-lock.json, package.json
The fix comes via ApiDOM@0.56.3 (apidom-ls)
Refs https://github.com/swagger-api/apidom/releases/tag/v0.56.3
=> fix: fix AsyncAPI 2.x Message.traits field lint rules

src/plugins/validate-semantic/selectors.js
This fix allow the selector to return Operations
Objects only, instead selecting all the keys
of Path Item Object.
Refs #3769
=> fix(validate-semantic): narrow allOperations selector

src/plugins/editor-monaco/actions.js, src/plugins/editor-monaco/components/MonacoEditor/MonacoEditorContainer.jsx, src/plugins/editor-monaco/components/ValidationPane/ValidationPane.jsx, src/plugins/editor-monaco/components/ValidationPane/ValidationPane.test.jsx, src/plugins/editor-monaco/index.js, src/plugins/editor-monaco/reducers.js, src/plugins/editor-monaco/selectors.js
Refs #3803
BREAKING CHANGE: editor.editorMarkers redux state has been changed to editor.markers. FSA updateEditorMarkers has been renamed to setEditorMarkers. Selector selectEditorMarkers has been renamed to selectMarkers.
=> feat(editor-monaco): add ability to use custom markers

release/.release-it.json
This allows to use lockfileVersion=2 in package-lock.json file.
Refs #2966
=> ci(release): add --legacy-peer-deps option for npm

src/plugins/editor-monaco-language-apidom/after-load.js, src/plugins/editor-monaco-language-apidom/language/actions/dereference.js, src/plugins/editor-monaco-language-apidom/language/monaco.contribution.js, src/plugins/editor-preview-asyncapi/util/raml-1-0-parser.js
- infere format (JSON/YAML) from editor content
- do nothing on unknown format
- use js-yaml library to pretty-format the dereferenced YAML
=> refactor(language-apidom): enhance dereference monaco action

package-lock.json, package.json
OpenAPI 3.1.0 components.schemas are rendered using new JSON Schema 2020-12 capable renderer.
Supported vocabularies:
This rendering support comes via swagger-ui-react@5.0.0-alpha.7.
Refs https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.7
=> feat(editor-preview-swagger-ui): render OpenAPI 3.1 Schema Objects

src/plugins/editor-monaco-language-apidom/language/adapters/DocumentLinkAdapter.js
Refs #3216
When converting `Document Links` with protocol converter which contains empty ranges, the error will be thrown. This fix avoids the error being thrown.
=> fix(language-apidom): aprovide document links with non-empty ranges

src/plugins/editor-monaco-language-apidom/actions/get-json-pointer-position.js, src/plugins/editor-monaco/actions/set-position.js, src/plugins/editor-monaco/components/MonacoEditor/MonacoEditor.jsx, src/plugins/editor-monaco/index.js, src/plugins/editor-monaco/reducers.js, src/plugins/editor-monaco/selectors.js, src/plugins/editor-textarea/components/TextareaEditor/TextareaEditor.jsx, src/plugins/editor-textarea/hooks.js, src/plugins/editor-textarea/index.js, src/plugins/editor-textarea/reducers.js, src/plugins/editor-textarea/selectors.js
If multiple <SwaggerEditor /> components are utilized on the same page, each of them should work independently without affecting the other ones.
=> fix: select editor instances in deterministic way

package-lock.json, package.json
Supported vocabularies:
- Core vocabulary
- Validation vocabulary
- OpenAPI 3.1.0 base vocabulary
Refs https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.12
=> feat(preview-swagger-ui): render JSON Schema 2020-12 in OpenAPI 3.1.0

README.md, package.json
Latest version of  `monaco-editor` and `@codingame/monaco-vscode-api` increased their size by around 800Kb. There is nothing we can currently do about it as `monaco-editor` doesn't support Language Server Protocol nativelly.
=> build: extend Node.js max heap limit to 4 BG

src/plugins/editor-monaco-language-apidom/language/apidom-mode.js
Customized providers (like the diagnostics provider) needs to be registered before monaco editor is created
and services are initialized.
=> fix(monaco-language-apidom): register diagnostics provider early

src/plugins/editor-content-fixtures/selectors/selectOpenAPI310PetstoreYAML.js
The goal is to align our OpenAPI 3.1.0 Petstore fixture
with linting rules so that the fixture doesn't produce any linting issues.
=> fix(editor-content-fixtures): amend OpenAPI 3.1.0 Petstore fixture

src/plugins/editor-monaco-language-apidom/language/apidom-mode.js, src/plugins/editor-monaco-language-apidom/language/monaco.contribution.js, src/plugins/editor-monaco-language-apidom/language/providers/DiagnosticsProvider.js, src/plugins/editor-monaco/after-load.js, src/plugins/editor-monaco/fn.js, src/plugins/editor-monaco/index.js, src/plugins/editor-monaco/root-injects.js
This will allow language plugins to inspect
the state of monaco/vscode initialization and
hook wherever and whenever needed.
---
Initialization of services only happens once.
Initialization of extensions happens after services initialization and happens only once as well.
If SwaggerEditor@5 is unmounted and mounted again the initialization is not run again. 
Initialization phases are now tracked in `window.MonacoEnvironment.initPhase`. 
SwaggerUI plugin system roon inject named `monacoInitializationDeferred` is now exposed to plugin system and can be used in following way:
```js
system.monacoInitializationDeferred().promise.then(() => {
console.dir('both services and extensions are now initialized');
});
```
=> fix(editor-monaco): track lifecycle of monaco/vscode initialization

src/App.jsx, src/plugins/editor-safe-render/components/ErrorBoundary.jsx, src/plugins/editor-safe-render/index.js, src/plugins/editor-safe-render/wrap-components/ErrorBoundaryWrapper.jsx
When following AsyncAPI definition was provided to the editor, the AsyncAPI renderer crashed, error boundary caught the error and displayed the fallback component. When we changed the editor content to fix the issue, the fallback component was still displaying, because it's error state was persistent. This is fine in SwaggerUI content, where the definition is immutable. But it's impractical in SwaggerEditor@5 content, where definition always changes. This PR introduces override for error boundary mechanism provided by SwaggerUI, which detects if editor has changed. If the editor content has changed the error boundary state resets.
**Definition**:
```yaml
asyncapi: '2.6.0'
info:
title: AsyncAPI
version: '1.0.0'
channels:
'foo':
description: Bar.
publish:
message:
oneOf:
- $ref: …
```
=> fix(editor-preview): reset error boundaries on editor content change

src/App.jsx, src/presets/monaco/index.js, src/presets/textarea/index.js
This will help in exposing the `presets` via package.json `exports` field in future.
=> feat: extract presets to reusable modules

src/plugins/editor-monaco-language-apidom/language/ApiDOMWorker.js
Refs #4409
Refs https://github.com/swagger-api/apidom/pull/3084
=> feat(monaco-language-apidom): switch to apidom-reference validation

package-lock.json, package.json
With these version we're parsing and rendering
AsyncAPI definition correctly.
Refs #4585
=> fix(editor-preview-asyncapi): use stable versions of AsyncAPI tooling

package-lock.json, package.json
Without pinning, the VSCode API can introduce
breaking changes in patch releases.
=> fix(monaco-editor): pin monaco-editor + VSCode combo

src/plugins/editor-monaco/after-load.js, src/plugins/editor-monaco/monaco-contribution/actions/go-to-symbol.js, src/plugins/editor-monaco/monaco-contribution/index.js
Refs https://github.com/CodinGame/monaco-vscode-api/issues/267
=> fix(editor-monaco): re-introduce Go To Symbol contextual menu item

.eslintrc, src/plugins/editor-monaco/monaco-contribution/index.js
Refs https://github.com/CodinGame/monaco-vscode-api/issues/267
=> fix(editor-monaco): display commands palette dialog

src/plugins/editor-monaco-language-apidom/language/providers/DiagnosticsProvider.js
OpenAPI 2.0 linting currently contains single
linting rule. More rules will come with time.
=> feat(language-apidom): enable linting for OpenAPI 2.0

package-lock.json, package.json, src/plugins/editor-monaco/after-load.js
The upstream vscode@1.83.16 now contains the fix.
=> fix(editor-monaco): remove workaroud code for services initialization

src/plugins/editor-content-fixtures/selectors/selectOpenAPI20PetstoreYAML.js, src/plugins/editor-content-fixtures/selectors/selectOpenAPI303PetstoreYAML.js, src/plugins/editor-content-fixtures/selectors/selectOpenAPI310PetstoreYAML.js
=> fix(content-fixtures): update to conform with OpenAPI 3.0.3 spec

src/plugins/json-schema-validator/index.js
Refs #4697
Explanation in https://github.com/swagger-api/swagger-editor/issues/4697#issuecomment-1893271111
=> fix(json-schema-validator): propertly handle unknown definition

test/cypress/e2e/plugin.editor-persistence.cy.js, test/cypress/support/commands.js
I've removed the code that case either causing issues when running tests or code that just did nothing.
Code that was causing the crashes was:
```js
cy.stub(win.console, 'warn', (msg) => {
cy.now('task', 'warn', msg);
});
```
=> test(cypress): make cypress tests run smoothly

README.md, package-lock.json, package.json, src/plugins/editor-monaco-language-apidom/language/monaco.contribution.js
=> feat: use VSCode API + Monaco Editor built from vscode@1.87.2

src/plugins/editor-content-type/actions.js, src/plugins/editor-preview-asyncapi/monaco.contribution.js, src/plugins/editor-preview-asyncapi/wrap-actions.js, src/plugins/editor-preview-asyncapi/wrap-components/EditorPreviewWrapper.jsx
=> feat(editor-preview-asyncapi): add initial support for AsyncAPI 3.0.0

src/plugins/editor-content-fixtures/index.js, src/plugins/editor-content-fixtures/selectors/selectAsyncAPI300StreetlightsYAML.js, src/plugins/top-bar/components/FileMenu/items/LoadExampleNestedMenu/LoadExampleNestedMenu.jsx, src/plugins/top-bar/components/FileMenu/items/LoadExampleNestedMenu/LoadExampleNestedMenuHandler.jsx, src/plugins/top-bar/components/FileMenu/items/LoadExampleNestedMenu/items/AsyncAPI30StreetlightsMenuItem.jsx, src/plugins/top-bar/index.js
=> feat(top-bar): add support for loading AsyncAPI Streetlights 3.0.0 example

README.md
yarn was misspelt as yarm
Refs #4940
=> docs(README): fix typo in the documentation

README.md, package-lock.json, package.json, swagger-editor-dist-package/README.md, swagger-editor-dist-package/package.json
Swagger Editor uses [Scarf](https://scarf.sh/) to collect [anonymized installation analytics](https://github.com/scarf-sh/scarf-js?tab=readme-ov-file#as-a-user-of-a-package-using-scarf-js-what-information-does-scarf-js-send-about-me). These analytics help support the maintainers of this library and ONLY run during installation. To [opt out](https://github.com/scarf-sh/scarf-js?tab=readme-ov-file#as-a-user-of-a-package-using-scarf-js-how-can-i-opt-out-of-analytics), you can set the `scarfSettings.enabled` field to `false` in your project's `package.json`:
```
// package.json
{
// ...
"scarfSettings": {
"enabled": false
}
// ...
}
```
Alternatively, you can set the environment variable `SCARF_ANALYTICS` to `false` as part of the environment that installs your npm packages, e.g., …
=> feat(analytics): use Scarf.js to provide anonymized installation analytics

src/plugins/swagger-ui-adapter/wrap-components/BaseLayout.jsx
Fixing condition in `BaseLayout` to handle properly AsyncAPI 3.x.x.
Rendering AsyncAPI 3.x.x properly with existing layouts.
Fixes #5358 
I ran tests using custom Layout with proposed implementation of BaseLayout.
=> fix: Render AsyncAPI 3+ properly with BaseLayout (#5358)

src/standalone/styles/topbar.less, src/styles/_dropdown-menu.less
Fixes #5490 
Fixes an issue where menu items are displayed outside of container
=> fix(menu): stretch menu list container to fit all items
