- app/scripts/directives/tryoperation.js
- app/scripts/templates.js
- app/templates/try-operation.html
> Bugfix for #340: switched consumes with produces in tryoperation.js and templates

- start.js
Trivial, sorry for the noise...
> Missing semicolon

- app/styles/main.less
- bower.json
> [build] use less version of bootstrap

- docs/config.md
> Fix typo in path

- app/scripts/directives/tryoperation.js
Add support for having multiple security requirements.
e.g. client ID and basic auth
> Multiplesecurity

- app/config/defaults.json
- app/spec-files/twitter.yaml
added the twitter api example to example folder
> added the twitter api example to example folder

- Dockerfile
Use solution from bower https://github.com/bower/bower/issues/866 resolve https://github.com/swagger-api/swagger-editor/issues/279
> bower install sometimes cannot work correctly in Docker build

- app/scripts/controllers/preview.js
- test/e2e/specs/5_session_auth_test.js
Detail:
1. It seem that the sessionStorage is reset by somewhere, so I delete
the default call of the sesstionStorage.
2. There some code deleted by you, I will restored later.
> Just fix the test

- README.md
standard npm badges added to readme
> npm badges added to readme

- docs/cors.md
Correcting apostrophe usage and improving readability.
> Apostrophe & readability fixes.

- app/styles/components/preview.less
- app/views/preview/preview.html
Add 'jump to YAML' icon to Definitions.
> [preview] Add jump-to-YAML icon

- bower.json
> [dependencies] update sway-worker

- .travis.yml
- Dockerfile
> updated Dockerfile to allow ci pushes with prebuilt code

- Dockerfile
Based on https://github.com/schickling/dockerfiles/blob/master/swagger-ui/Dockerfile
> Reduce image size from 359.1 MB to 54.68 MB

- grunt/copy.js
Fixes: https://github.com/swagger-api/swagger-editor/issues/773
> [build] Copy ace keybindng files to dist

- app/styles/components/modal.less
> [Less] Update paste.json textarea color

- app/styles/components/editor.less
> [Less] Update search box styling

- Dockerfile
> Use the correct http-server flag

- app/styles/components/path-headers.less
- app/styles/markdown.less
> [Less] Correct the font size in markdown list and table

- app/scripts/controllers/header.js
Please refer to https://github.com/swagger-api/swagger-codegen/pull/1966 for more information.
We need to coordinate this change with https://github.com/swagger-api/swagger-codegen/pull/1966
> Rename nodejs to nodejs-server

- index.js
- package.json
- styles/main.less
es6-shim polyfill to fix IE10 missing functions
> es6-shim to polyfill missing IE10 es6 functions (Map and Set)

- styles/components/menu-bar.less
- views/header/header.html
> Change 'Generate Server' and 'Generate Client' list into more columns

- scripts/directives/tryoperation.js
> Set message on error

- scripts/app.js
- scripts/config.js
- scripts/router.js
> Sanitize outputs and move configs to a new file

- .travis.yml
Fixes #860 
@fehguy please review
> deploy to npm using TravisCI

- package.json
- webpack.config.js
Fixes https://github.com/swagger-api/swagger-editor/issues/930
> Fix absolute path issue by using url-loader instead of file loader

- scripts/directives/tryoperation.js
> merge allOf instead if assign

- package.json
> fix gh-pages script

- .travis.yml
@saharj please see if this works to fix #947
> changed to push only on tag

- scripts/controllers/tryoperation.js
- test/unit/spec/controllers/tryoperation/generateUrl.js
> Encoding special characters

- .eslintrc.js
- scripts/controllers/tryoperation.js
- test/unit/spec/controllers/tryoperation/makeRequestModel.js
<Please provide screenshot of UI changes in this pull request>
> Try operation

- config/defaults.json
- config/defaults.json.guide.js
- scripts/controllers/paste-json.js
- scripts/controllers/preferences.js
- scripts/controllers/preview.js
- scripts/services/builder.js
- scripts/services/preferences.js
- templates/preferences.html
Fixes https://github.com/swagger-api/swagger-editor/issues/977
See [this comment](https://github.com/swagger-api/swagger-editor/issues/977#issuecomment-232254578)
> JSON References resolve base path

- webpack.config.js
See commit message: https://github.com/swagger-api/swagger-editor/pull/1007/commits/387511e70ccd717abd61389c28224fc43d110f20
> Small message grammar fix

- scripts/bootstrap.js
- webpack.config.js
> Add missing templates

- scripts/controllers/tryoperation.js
- test/unit/spec/controllers/tryoperation/generateUrl.js
There is no UI changes
Now editor build URI in tryout according to specification when using:
```yaml
in: query
type: array
collectionFormat: csv|ssv|tsv|pipes|multi
```
> fixed #776

- scripts/controllers/tryoperation.js
> Submit file parameters with FormData

- docs/development.md
> Release documentation

- scripts/controllers/main.js
- scripts/services/fileloader.js
Making import experience a bit better by not removing import url query parameter 
#1195
> do not remove import URL from query string

- src/plugins/editor/components/editor.jsx
- src/plugins/topbar/topbar.less
- modified editor text size
- styled topbar menu
- made splitpane wrapper hide container scrollbar
> Styling updates to header and wrapper

- .gitignore
- package.json
> Testing fixes

- .babelrc
- .eslintcache
- .eslintrc
- .gitignore
- package.json
- test/.eslintrc
- test/plugins/ast/ast-manager.js
- test/plugins/validation/semantic/form-data.js
- test/plugins/validation/semantic/operations.js
- test/plugins/validation/semantic/paths.js
- test/plugins/validation/semantic/schema.js
- test/plugins/validation/semantic/walker.js
Adds testing and linting to `npm test`.
> Testing and linting

- package.json
- src/plugins/topbar/topbar.jsx
> Add JSON prettifier

- src/plugins/editor/components/editor.jsx
- src/plugins/editor/components/editor.less
- src/plugins/topbar/topbar.less
for #1232 
- Safari now displays the code editor
> updated styling for safari browser

- package.json
- src/plugins/topbar/topbar.jsx
- src/plugins/topbar/topbar.less
Fixes #1228.
- `File > Import URL` menu item
- `File > Import File` menu item
- `Edit > Convert to YAML` menu item
> Document Import

- .travis.yml
- Dockerfile
- docker-run.sh
- nginx.conf
> added docker files

- src/plugins/validation/semantic-validators/validators/security.js
- test/plugins/validation/semantic/security.js
Fixes #1259.
Also adds tests for security validation.
> Fix and improve security validation

- .gitignore
See https://github.com/swagger-api/swagger-ui/pull/3058.
> gitignore all npm-debug logs

- src/plugins/topbar/topbar.jsx
Supersedes https://github.com/swagger-api/swagger-editor/pull/1314
> change generator URL to use https so they are not blocked

- src/plugins/editor/components/editor.less
- src/plugins/editor/components/read-only-watermark.less
- src/standalone/topbar/topbar.less
Only apply styles in editor.less to #swagger-editor and under
Also add read-only styling ( ie: the read only watermark )
> Only apply styles in editor.less to #swagger-editor and under

- src/standalone/topbar/topbar.jsx
> Convert all URL-import specs to YAML

- README.md
for https://github.com/swagger-api/swagger-editor/issues/1312
> Add security contact to README

- src/standalone/topbar/topbar.jsx
> Convert to YAML when importing file

- src/standalone/topbar/topbar.jsx
> Send unresolved spec to Codegen service

- src/plugins/validation/semantic-validators/validators/items-required-for-array-objects.js
Fixes #1473.
I wrote a whole semantic validator for this, before realizing that we were already doing this in another place... I'll take the one-liner 😄
> Run properties grandchildren through Schema validation

- README.md
CC https://github.com/swagger-api/swagger-editor/issues/1423#issuecomment-331451421
> Add npm module summary to README

- src/plugins/validation/semantic-validators/validators/parameters.js
- test/plugins/validation/semantic/parameters.js
> Add error for non-body parameters that don't provide a type

- Dockerfile
- make-webpack-config.js
- webpack-hot-dev-server.config.js
This PR:
- Updates static build and dev server `devtool` settings to match https://github.com/swagger-api/swagger-ui/pull/3793
- Adds source map files to Swagger-Editor Docker images
> Sourcemaps

- src/plugins/editor/components/editor.jsx
> Silence "Automatically scrolling cursor into view"

- src/plugins/jump-to-path/spec.js
EZ!
Fixes https://github.com/swagger-api/swagger-editor/issues/1613.
> Reconcile new Immutable specPath with getLineNumberForPath helper

- src/standalone/topbar/topbar.jsx
> Pass in the framework name variable to handleResponse

- src/standalone/topbar/topbar.jsx
> Don't display file name in File menu

- .travis.yml
> Remove docker login `--email` flag

- src/plugins/validate-semantic/helpers.js
- src/plugins/validate-semantic/validators/2and3/parameters.js
- src/plugins/validate-semantic/validators/form-data.js
- test/plugins/validate-semantic/form-data.js
> fix: consumes semantic validation consideration of global consumes

- Dockerfile
> Copy favicon files into Docker image

- src/plugins/validate-semantic/validators/2and3/refs.js
- test/plugins/validate-semantic/2and3/refs.js
Fixes https://github.com/swagger-api/swagger-editor/issues/1702.
> fix(semval): don't fail on well-formed remote full document refs

- .travis.yml
> fix  error in Docker tag deployer

- .travis.yml
> trigger Docker deployer on tag builds

- .travis.yml
- build-tools/deploy-docker-hub-tag.sh
> break tag deployer out into its own `build-tools` script

- src/plugins/validate-semantic/validators/2and3/parameters.js
- test/plugins/validate-semantic/2and3/parameters.js
- test/plugins/validate-semantic/2and3/refs.js
- test/plugins/validate-semantic/validate-helper.js
No ticket; just something I observed.
> fix: parse root parameter objects correctly

- src/plugins/validate-semantic/validators/2and3/parameters.js
- test/plugins/validate-semantic/2and3/parameters.js
Fixes https://github.com/swagger-api/swagger-editor/issues/1738.
> fix: don't validate for uniqueness against root parameters

- src/index.js
> fix(generator-integration): use HTTPS, always, forever

- src/plugins/validate-semantic/index.js
- src/plugins/validate-semantic/selectors.js
- src/plugins/validate-semantic/validators/2and3/schemas.js
- src/plugins/validate-semantic/validators/schema.js
- test/plugins/validate-semantic/2and3/schemas.js
> improve(validation): array schema `items`

- src/plugins/validate-semantic/selectors.js
- test/plugins/selectors.js
> fix(semval): subject OAS3 req/res schemas to schema validation

- README.md
"A man is judged by the README.md that he keeps" - Aesop
> docs: README touchups

- src/index.js
> fix(codegen-integration): use `swagger.json` for Generator 3 URL

- src/plugins/local-storage/petstore.js
Fixes https://github.com/swagger-api/swagger-editor/issues/1736.
> improvement: add HTTPS scheme to default Petstore doc

- src/plugins/jump-to-path/components.jsx
Related to https://github.com/swagger-api/swagger-editor/issues/1791 and https://github.com/swagger-api/swagger-ui/pull/4674.
> improvement: add title attr to JumpToPath img

- src/standalone/topbar/topbar.jsx
- src/standalone/topbar/topbar.less
> fix: modal height CSS bug

- package.json
- src/index.js
Fixes #1846, and a privately reported issue.
> bugfix: import missing AST plugin

- src/plugins/editor/components/editor.jsx
Make updating the YAML in the editor more robust.
There are edge cases, where the yaml will roll back. And the markers will fall out of sync. 
The bulk of those cases were solved, but some remained.
Manually, automation pending...
> add stricter tests for updating yaml and markers

- src/polyfills.js
> remove duplicated import

- LICENSE
> housekeeping: happy new year!

- src/plugins/validate-semantic/selectors.js
- src/plugins/validate-semantic/validators/2and3/parameters.js
- test/unit/plugins/validate-semantic/2and3/parameters.js
> fix(semval): cover OAS3 global parameters and handle referenced param content

- package-lock.json
- package.json
This PR updates the minimum Cypress version in `devDependencies`.
https://github.com/cypress-io/cypress/issues/2861
> housekeeping: bump minimum Cypress version

- package-lock.json
- package.json
- src/plugins/editor/editor-plugins/json-to-yaml.js
- src/plugins/json-schema-validator/index.js
- src/standalone/topbar-insert/forms/components/AddForm.jsx
- src/standalone/topbar-menu-file-import_file/components/ImportFileMenuItem.jsx
- src/standalone/topbar/topbar.jsx
- test/unit/plugins/json-schema-validator/index.js
- webpack/_config-builder.js
coordinated with:
* https://github.com/swagger-api/swagger-js/pull/1459
* https://github.com/swagger-api/swagger-ui/pull/5511
> housekeeping: `@kyleshockey/js-yaml` -> `js-yaml`

- src/plugins/json-schema-validator/oas3-schema.yaml
- src/plugins/json-schema-validator/swagger2-schema.yaml
- src/plugins/validate-semantic/index.js
- src/plugins/validate-semantic/selectors.js
- src/plugins/validate-semantic/validators/2and3/tags.js
- test/unit/plugins/json-schema-validator/test-documents/tag-object-uniqueness.yaml
- test/unit/plugins/validate-semantic/2and3/tags.js
> fix: Tag Object uniqueness validation

- package-lock.json
- package.json
> housekeeping: install `@release-it/conventional-changelog`

- package-lock.json
- package.json
> `npm audit fix`

- LICENSE
> 2️⃣0️⃣2️⃣0️⃣

- .eslintrc
- package-lock.json
- package.json
- test/unit/plugins/validate-semantic/form-data.js
oops! accidentally introduced this in #2115 — this PR drops the exclusive test and adds an ESLint rule preventing such a change in the future.
> housekeeping: fix exclusive Mocha test case

- package-lock.json
- package.json
update http-server to latest to fix app not starting
see https://github.com/http-party/http-server/issues/525
fixes #2106 
editor didn't open, now it does.
environment is same as reporter (me)
- [x ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ x] Dependency changes (any modification to dependencies in `package.json`)
- [ x] Bug fixes (non-breaking change which fixes an issue)
- [ x] are not breaking changes.
- [ x] My changes do not require a change to the project documentation.
- [ x] My changes can not or do not need to be tested.
note: nothing I changed should effect tests, but I am unable to confirm this, as tests are failing on my system at random, likely due to the company installed antivirus I cannot disable.  Different amounts of tests …
> fix for invalid redirect error http-server#525

- package-lock.json
- package.json
swagger-client@3.10.6
swagger-ui@3.26.0
bump SwaggerClient and SwaggerUI release versions
> housekeeping: swagger-client and swagger-ui version bump

- docker-run.sh
> fix: bad conditional in `docker-run.sh`

- release/.release-it.json
Align release commit message with conventional commit specification.
> build(release-it): configure proper release commit msg

- package-lock.json
- package.json
update dependency to sync with swagger-ui
> chore(deps-dev): update @babel/runtime-corejs2 from 7.0.0 to 7.10.4

- src/polyfills.js
remove the actual file `/src/polyfills.js`
swagger-editor no longer uses polyfills. This file is no longer in use.
- [] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
> chore: remove unused deprecated polyfill.js file

- package-lock.json
* resolves vulnerability in node-forge < 0.10.0
update node-forge dependency
`npm run dev` still works.
> chore(deps-dev): update selfsigned from 1.10.7 to 1.10.8

- package-lock.json
- package.json
> chore(deps-dev): cypress@5.3.0

- Dockerfile
Update to use nginx 1.19. 1.17 is now end of life and mainline is now 1.19
Uses newer supported version of nginx for security and related fixes
- [x ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ x] are not breaking changes.
- [ x] My changes do not require a change to the project documentation.
- [ x ] All new and existing tests passed.
> Update dockerfile to nginx 1.19

- README.md
Fix a typoin docs at testing section.
fixes #2237 
This change does not affect anything
> Fix: fix docs typo

- test/unit/setup.js
- Attempt to fix #2223 by unsetting `XMLHttpRequest`.
- Run `npm audit fix` to fix some low severity warnings
- Fix a typo in README file
- Add .vscode to .gitignore
Resolves  #2223
> fix: run npm audit fix; fix Jest CORS null forbidden

- src/styles/main.less
Override ace editor default width for autocomplete from 280px to 50%
Fixes #2240
visual inspection
> refactor(style): increase ace editor autocomplete width

- .github/workflows/nodejs.yml
Initial github actions for CI. No changes to `package.json`
Migrate from Jenkins CI
> ci(GA): use github actions for CI

- .github/workflows/nodejs.yml
Add release step to github actions
CI
> ci(GA): add release step

- .github/workflows/nodejs.yml
* Add an independent job to build and run artifact tests.
* parallel job reduces net time to complete CI. e2e and building bundles for artifact tests each take some time.
* parallel job enables targeting different Node versions per job
add `test:artifact` to CI. Previously not included.
> ci(GA): add test:artifact job

- .github/workflows/nodejs.yml
Add `lint-errors` step to build job.
part of extracting `lint-errors` from `npm test`, to control tests more explicitly in GA.
> ci(GA): add lint-errors step

- nginx.conf
Add `server_tokens off` to `nginx.conf`
Nginx security configuration harden guide: https://wiki.owasp.org/index.php/SCG_WS_nginx
> security(docker): hide nginx version

- package-lock.json
> chore(deps): bump ini to 1.3.7

- package-lock.json
- package.json
update dependencies, including `node-fetch` sub-dependency
> chore(deps-dev): release-it@13.7.1

- .github/dependabot.yaml
Daily dependabot check.
Intending to migrate from Renovate-bot to Dependabot.
Github Action to auto-merge passing dependabot PRs.
> ci: dependabot yaml config

- .github/workflows/nodejs.yml
Move "Merge me" GA as last job, per recommendation of [docs](https://github.com/ridedott/merge-me-action)
> refactor(GA): move merge-me to eof

- package-lock.json
- package.json
Remove `bundlesize` dev dependency
remove unused dependencies. for swagger-editor, webpack is configured to perform size checkes.
> chore(deps-dev): remove unused bundlesize

- package-lock.json
- package.json
Reverts swagger-api/swagger-editor#2293
> Revert "chore(deps-dev): bump mini-css-extract-plugin from 0.9.0 to 1.3.3"

- package-lock.json
- package.json
Remove the unused dependency `core-js`.
remove unused dependencies.
> chore(deps): remove unused core-js

- package-lock.json
- package.json
bump `style-loader` to v1.3.0
update dependencies
local `npm run dev` continues to compile properly.
> chore(deps-dev): bump style-loader to v1.3.0

- package-lock.json
- package.json
remove `matcher` dev dependency
remove unused dependencies
> chore(deps-dev): remove unused matcher

- package-lock.json
- package.json
bump swagger-ui@3.39.0 to swagger-ui@3.40.0
release job did not auto-update to swagger-ui@latest
> chore(deps): bump swagger-ui to 3.40.0

- package-lock.json
- package.json
bump swagger-client from 3.12.1 to 3.12.2
release build did not update swagger-client
> chore(deps): bump swagger-client from 3.12.1 to 3.12.2

- .github/workflows/dependabot-merge.yml
Reduce interval time from 360 seconds to 180 seconds.
reduce delay between merge attempts.
> ci(dependabot): reduce interval time

- package-lock.json
- package.json
bump cypress from 5.3.0 to 6.8.0
update dependency
> chore(deps-dev): bump cypress from 5.3.0 to 6.8.0

- package-lock.json
bump elliptic to 6.5.4
`npm audit`; "Use of a Broken or Risky Cryptographic Algorithm"
> chore(deps-dev): bump elliptic to 6.5.4

- package-lock.json
bump ssri from 8.0.0 to 8.0.1
update dependencies
> chore(deps-dev): bump ssri from 8.0.0 to 8.0.1

- README.md
- docs/import.md
As per #1352, the functionality for importing an OpenAPI specification `yaml` is working via the `?url=` parameter. It is not a known issue.
1. remove from "known issues" (as it is functioning)
2. add/update a note to the import documentation accordingly
yes; tested against :heavy_check_mark: 
https://editor.swagger.io/?url=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/yaml/api-with-examples.yaml
> Denote support for url=? parameter to import spec and remove from known issues in readme.

- docs/import.md
Changes are restricted in scope to docs. 
Typo corrected: publically => publicly
Change is in agreement with Standard American English.
n/a
- [x ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [x ] are not breaking changes.
- [x ] My changes require a change to the project documentation.
- [x ] If yes to above: I have updated the documentation accordingly.
- [x ] My changes can not or do not need to be tested.
> fix(docs): corrects typo in project documentation

- package-lock.json
bump url-parse from 1.4.7 to 1.5.1
dependency update, with security update
> chore(deps-dev): bump url-parse from 1.4.7 to 1.5.1

- package-lock.json
bump handlebars from 4.7.6 to 4.7.7
update dependency, with security update
> chore(deps-dev): bump handlebars from 4.7.6 to 4.7.7

- package-lock.json
bump hosted-git-info from 2.7.1 to 2.8.0
update dependencies, with security update
> chore(deps-dev): bump hosted-git-info from 2.7.1 to 2.8.0

- package-lock.json
- package.json
bump eslint-plugin-jest from 23.20.0 to 24.3.6
update dependency.
> chore(deps-dev): bump eslint-plugin-jest from 23.20.0 to 24.3.6

- package-lock.json
update caniuse-lite to 1.0.30001230
update db for `browserslist`
> chore(deps-dev): update caniuse-lite to 1.0.30001230

- package-lock.json
- package.json
bump cypress from 6.8.0 to 7.5.0
update dependencies. Node v12 required.
replaces #2671 from dependabot
existing tests pass
> chore(deps-dev): bump cypress from 6.8.0 to 7.5.0

- .husky/commit-msg
- .husky/pre-commit
> chore: add husky hooks

- package-lock.json
> chore(security): fix npm vulnerabilities

- package-lock.json
> chore(package-lock): add integrity check for ssri lib

- package-lock.json
- package.json
Refs https://github.com/swagger-api/swagger-ui/issues/7436
> fix(deps): update SwaggerUI to v3.51.2

- package-lock.json
- package.json
> Dependencies security fixes

- Dockerfile
- package-lock.json
Refs https://github.com/swagger-api/swagger-ui/issues/7445
> fix(dockerfile): fix security issue in docker image

- .github/_dependabot_.yaml
- .github/workflows/docker-image-check.yml
> chore(docker): automatic updates + nightly security check

- package-lock.json
- package.json
- src/plugins/jump-to-path/index.js
- src/plugins/jump-to-path/jump-to-path.jsx
Main fix was introduced as part of swagger-ui@4.1.2.
Refs #2099
> fix: fix crashing the editor after refresh

- docker-run.sh
- index.html
- package-lock.json
- package.json
- test/e2e/static/index.html
> fix(security): update SwaggerUI

- .github/workflows/nodejs.yml
- config/jest/jest.artifact-es-bundle-core.config.js
- config/jest/jest.artifact-es-bundle.config.js
- config/jest/jest.artifact.config.js
- package-lock.json
- package.json
> ci(GA): optimize workflows

- webpack/_config-builder.js
> build(webpack): eliminate duplicates in build fragments

- README.md
This change is effect of https://github.com/swagger-api/swagger-editor/commit/1a6bba7dd2cd239d6c403da2086141fd2f23e5bd
> docs(README): change supported Node.js versions

- src/index.js
Refs #2844
By inspecting React component tree
> refactor: utilize error boundaries via safe-render plugin

- package-lock.json
Refs https://github.com/swagger-api/oss-planning/issues/529
> chore(security): fix security vulnerabilities in deps

- package-lock.json
- package.json
- src/plugins/json-schema-validator/validator/index.js
Refs https://github.com/swagger-api/oss-planning/issues/529
> chore(security): resolve security vulnerability in ajv

- release/.release-it.json
> chore(release): amend release hooks

- package-lock.json
- package.json
- webpack/_config-builder.js
Before this fix React was bundles twice
and could cause various side effects
Closes #2915
> fix(build): bundle React just once

- README.md
> docs(README): remove dependencies badges

- package.json
> Fix Missing npm script

- config/jest/jest.artifact.config.js
- config/jest/jest.unit.config.js
- package-lock.json
- package.json
- webpack/_config-builder.js
> fix(build): fix missing code fragments in build fragments

- webpack/es-bundle.babel.js
> build: add support for Create React App

- package-lock.json
- package.json
Add dev dependency `react-refresh`
Enables `npm run dev` to work. More specifically, `@pmmmwh/react-refresh-webpack-plugin` requires `react-refresh>0.10.0`, which was a missing dev dependency
followup to #2998 
refs: #2944
local dev mode `npm run dev` now works
> chore(deps-dev): react-refresh@0.12.0

- package-lock.json
Refs https://github.com/swagger-api/swagger-editor/security/dependabot/31
> chore(security): fix vulnerabilities in dev deps

- src/standalone/topbar-menu-edit-convert/components/convert-definition-menu-item.jsx
- src/standalone/topbar/topbar.jsx
> refactor(topbar): fix inverse predicate logic

- .github/workflows/build.yml
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/deploy-rancher.yml
SwaggerEditor@next. Update github actions to reflect `next` branch.
> build(ga): update target branch and descriptions

- .github/workflows/nightly-build.yml
SwaggerEditor@next. Update github action for nightly build
> build(ga): update nightly build branch and name

- .github/workflows/nightly-build.yml
> chore(ga): update nightly build checkout

- .github/dependabot.yaml
Add a job section for SwaggerEditor@next branch, and add the `swagger-editor@next` label
Run daily Dependabot specifically for the `swagger-editor:next` branch. Hopefully no changes needed for the Github action "Merge Me!"
> chore(dependabot): schedule daily for @next branch

- .github/workflows/nightly-build.yml
SwaggerEditor@next nightly build
SwaggerEditor@next nightly build via `next` branch.
> chore(ga): nightly build for @next branch

- .github/dependabot.yaml
This more reflects what we need dependabot to update on `next` branch
- package.json and package-lock.json
- github actions
- Dockerfile
> chore(dependabot): update config for next branch

- .github/workflows/release.yml
This reverts commit 42c24d20c9b67d805bf33ef75e842ea8a8ed4ab8.
Having release workflow is required to be able
to it from Actions tab.
> revert: ci(GA): remove release workflow from master branch (#3155)

- .github/workflows/nightly-build.yml
SwaggerEditor@next. change cron time
more friendly US/west schedule
> ci(ga): update nightly build cron schedule

- .eslintrc
- package-lock.json
- package.json
> chore(deps): update ApiDOM to v0.31.1

- .env
- README.md
- public/static/petstore-oas3.yml
- src/index.jsx
* docs: add custom env section
Two environment variables are newly available: `REACT_APP_SWAGGER_FILE` and `REACT_APP_SWAGGER_URL`
* `REACT_APP_SWAGGER_FILE` specifies a local file path, and the specified file must also be present in the `/public/static` directory.
* `REACT_APP_SWAGGER_URL` specifies a remote URL. This environment variable currently takes precedence over `REACT_APP_SWAGGER_FILE`.
Documentation added, including sample environment flag settings.
Note: build with Docker custom env is not currently supported. Refer to docs in this PR.
Provide a method for users to specify an initial definition for SwaggerEditor to load. Bonus if can also use Docker.
Locally tested with both URL and local file use cases.
> feat: custom env for SWAGGER_URL and SWAGGER_FILE

- src/plugins/editor-monaco/workers/apidom/adapters/DefinitionAdapter.js
fixes #swagger-api/apidom/issues/1724
> fix: fix go to definition

- test/cypress/integration/editor-persistence.spec.js
- test/cypress/support/commands.js
> test(cypress): fix flaky persistent e2e test

- .env
apply `REACT_APP_DEFINITION_URL` and `REACT_APP_DEFINITION_FILE` to instructions/comments
consistency of naming
n/a
> refactor: apply renaming changes to comments

- src/plugins/editor-content-fixtures/fixtures/petstore-oas3.yml
- src/plugins/editor-content-fixtures/index.js
- src/plugins/editor-content-fixtures/selectors/selectOpenAPI20PetstoreYAML.js
- src/plugins/editor-content-fixtures/selectors/selectOpenAPI30PetstoreYAML.js
- src/plugins/top-bar/components/EditMenu/EditMenu.jsx
- src/plugins/top-bar/components/EditMenu/EditMenuHandler.jsx
- src/plugins/top-bar/components/EditMenu/items/LoadAsyncAPI24FixtureMenuItem.jsx
- src/plugins/top-bar/components/EditMenu/items/LoadOpenAPI20PetstoreFixtureMenuItem.jsx
- src/plugins/top-bar/components/EditMenu/items/LoadOpenAPI30PetstoreFixtureMenuItem.jsx
- src/plugins/top-bar/index.js
- test/cypress/integration/plugin.top-bar.spec.js
- editor-content-fixtures plugin now includes both Swagger Petstore OAS2.0 and OAS3.0 definitions.
- topbar plugin now renders Edit menu items for both Swagger Petstore OAS2.0 and OAS3.0 definitions.
- Swagger Petstore OAS2.0 and OAS3.0 definitions are YAML strings in JS format. e.g. not true `.yaml` file. This is to avoid needing to `fetch` external files.
- reorganized Edit menu list items, where "official" Swagger Petstore and "official" AsyncAPI Streetlights definitions reside in their own distinct grouping.
Provide "official" Swagger Petstore OAS2.0 and OAS3.0 definitions. Also note, legacy SwaggerEditor recently changed to Petstore OAS3.0 to its default definition.
local
> feat: fixtures for Swagger Petstore definitions

- test/cypress/integration/plugin.top-bar.spec.js
* Migrate many (removed) Jest test to Cypress
There are some (removed) Jest tests with mocks that are not practically replicable with Cypress. Explanations have been added in test comments.
Jest tests were removed in #3241 . Restore the relevant tests that were focused on user interactions.
These are new tests
> feat(test): migrate `topbar` Jest tests to Cypress

- test/cypress/integration/plugin.editor-monaco.spec.js
- test/cypress/integration/plugin.editor-read-only.spec.js
* [feat(test): e2e theme toggle](https://github.com/swagger-api/swagger-editor/commit/f5e6b73f3871291d90ccbb8c8ca6a7615aac0cbc)
* [feat(test): read-only toggle](https://github.com/swagger-api/swagger-editor/commit/8138741265f375fd67ff14bb63988f7f3124569c)
Add BDD test coverage.
These are new tests
> feat(test): e2e for toggle readonly and toggle theme

- package-lock.json
- package.json
- src/plugins/editor-monaco/components/MonacoEditor/MonacoEditor.jsx
> chore(deps): update monaco-editor-core to v0.34.0

- test/cypress/fixtures/streetlights-kafka.yml
* change the `clientId` definition
* minor styling updates
This `clientId` change matches the Edit Menu -> Load AsyncApi 2.4 Streetlights Fixture.
Note: there exists a skipped test in `plugin.editor-persistence.spec.js` that would need to get updated if re-enabled. This is due to the quotes change on line 1. e.g `asyncapi: '2.4.0'` -> `asyncapi: 2.4.0`
`plugin.validation-pane.spec.js` could intermittently fail due to ApiDOM detecting a parser error. The original `clientId` definition section also results in an ApiDOM parser error on editor-next.swagger.io, so this is not limited to a CI error. See screenshot
local `cy:ci`, electron, chrome
> test: update cypress asyncapi fixture

- package-lock.json
- package.json
> chore(deps): update monaco-languageclient to v4.0.1-next.0

- src/plugins/editor-monaco/components/MonacoEditor/MonacoEditor.jsx
- src/plugins/editor-monaco/workers/apidom/adapters/DefinitionAdapter.js
- src/plugins/editor-monaco/workers/apidom/adapters/DiagnosticsAdapter.js
- src/plugins/editor-monaco/workers/apidom/apidom-mode.js
> Regression elimination after removing monaco-languagclient

- src/standalone/topbar/topbar.jsx
Fixes :- #3530 
Fixed typos in topbar.jsx
> Fixed typos in topbar.jsx

- .github/workflows/nodejs.yml
* Use one step to cache node modules and Cypress binary
* Reference `CYPRESS_CACHE_FOLDER` inside cache step
It simplifies the `nodejs.yml` workflow
> Refactor nodejs.yml workflow

- package-lock.json
Refs https://github.com/swagger-api/swagger-editor/actions/runs/3263279521/jobs/5433950540#step:6:8
> chore(package-lock): fix fsevents installation

- .browserslistrc
> feat(browserslist): produce artifacts against modern desktop browsers

- .github/dependabot.yaml
> chore(dependabot): ignore react-scripts

- .gitattributes
- .gitmodules
- .prettierrc
Kudos to @frankkilcommins to pointing this out.
> chore: add better support for Windows dev setup

- .github/workflows/deploy-gh-pages.yml
- .github/workflows/deploy-rancher.yml
> ci: limit workflows based on branches

- package.json
- src/plugins/top-bar/components/AboutMenu/AboutMenu.jsx
- src/plugins/top-bar/components/Logo/Logo.jsx
- src/plugins/top-bar/components/TopBar/TopBar.jsx
- src/plugins/top-bar/index.js
- test/cypress/integration/plugin.top-bar.spec.js
Updated Home anchor link + added new About menu to TopBar which links to various documentation and product related material for Swagger-Editor@Next
fixes #3646
closes #3646
> Add About Menu to TopBar for swagger-editor@next

- .github/workflows/deploy-rancher.yml
> chore(docker): add support for multi platform docker image

- .github/workflows/deploy-rancher.yml
> ci(deploy-rancher): fix typo in platform list

- .github/workflows/deploy-rancher.yml
- .github/workflows/docker-build-push.yml
> ci: separate docker image build/push and deploy to separate workflows

- .github/workflows/deploy-rancher.yml
- .github/workflows/docker-build-push.yml
> ci: reflect changes to GitHub workflows from master

- .github/workflows/deploy-rancher.yml
- .github/workflows/docker-build-push.yml
> ci: enable Rancher deploy workflow

- .github/workflows/deploy-rancher.yml
- .github/workflows/release.yml
> ci: deploy SwaggerEditor@next to Rancher on successful release

- .github/workflows/deploy-rancher.yml
- .github/workflows/docker-build-push.yml
- .github/workflows/release.yml
> ci: build Docker image and deploy to Rancher on release

- .github/workflows/release.yml
> ci(release): test release dry run to determine the version

- .github/workflows/docker-build-push.yml
- .github/workflows/release.yml
> ci(release): add proper version to npm dist fragments

- .github/workflows/dependabot-merge.yml
Refs https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/166
> ci(dependabot-merge): replace non-functioning merge action

- .github/workflows/docker-build-push.yml
- Dockerfile.unprivileged
- README.md
Co-authored-by: marius-boden-sva
Refs #3033
Refs #3697
> feat(docker): build and publish unpriviledged image

- package-lock.json
- package.json
Closes #3727
Closes #3724
Closes #3725
> chore(deps-dev): update dev dependencies

- package-lock.json
- package.json
Closes #3778
Closes #3777
Closes #3775
> chore(deps-dev): update number of dev deps

- package-lock.json
- package.json
Closes #3811
Closes #3810
Closes #3809
> chore(deps): update number of deps

- .github/workflows/docker-build-push.yml
- .github/workflows/release.yml
- .npmignore
- README.md
- docs/customization/plug-points/editor-monaco.md
- package-lock.json
- package.json
Refs #3900
Refs #3907
Refs #3906
Refs #3901
> feat: publish npm package on npmjs.com registry

- .github/workflows/docker-build-push.yml
> ci(docker-build-push): access version info from parent workflow

- .github/workflows/docker-build-push.yml
- .github/workflows/nightly-build.yml
- .github/workflows/release.yml
> ci: reflect changes made in next branch

- package-lock.json
- package.json
- swagger-ui@4.17.1
- swagger-client@3.19.0
> feat: utilize latest versions of swagger-ui & swagger-client

- Dockerfile
- README.md
- docker-run.sh
- nginx.conf
`docker-run` cleanup
`Dockerfile` update - remove custom CMD, unneded commands
`nginx.conf` convert to template
`README.md` rephrasing
This change removes nginx container customization and use default nginx ecosystem, such as [Templating](https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119) and external scripts execution.
Enable custom port support if needed to remap it.
No need to copy and replace `CMD` parts of nginx container, ensure simplicity to run and security by only needed access rights (remove `chmod -R a+rw`). Use templating to apply Variables, such as `BASE_URL` and `NGINX_PORT`.
Container was build and executed with various parameters.
> Docker update

- package-lock.json
- package.json
Refs https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.6 
Closes #4005
Closes #4004
Closes #4003
> fix(editor-preview-swagger-ui): open Path Items containing schemas with cycles

- package-lock.json
- package.json
Refs https://github.com/CodinGame/monaco-vscode-api/issues/90
> build: get rid of vscode mp3 build fragments

- package-lock.json
- package.json
The fix comes via @codingame/monaco-vscode-api@1.76.7.
Refs #4014
> fix(build): avoid producing *.mp3 build artifacts

- src/plugins/top-bar/components/FileMenu/items/DownloadResolvedJSONMenuItemHandler.jsx
- src/plugins/top-bar/components/FileMenu/items/DownloadResolvedYAMLMenuItemHandler.jsx
> fix(top-bar): fix bug in 'Download Resolved JSON/YAML' menu items

- package-lock.json
- package.json
This change is specific to OpenAPI 3.1.0 definitions.
Refs https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.13
> feat(preview-swagger-ui): render Schemas

- .github/workflows/docker-build-push.yml
> ci(docker): disable provenance option

- package-lock.json
- package.json
Closes #4195 
Closes #4184 
Closes #4175
> feat(editor-preview-swagger-ui): integrate stable swagger-ui-react@5.0.0

- package-lock.json
- package.json
- src/plugins/editor-monaco/fn.js
- src/plugins/editor-monaco/index.js
- src/plugins/editor-preview-asyncapi/after-load.js
- src/plugins/editor-preview-asyncapi/components/EditorPreviewAsyncAPI/EditorPreviewAsyncAPI.jsx
- src/plugins/editor-preview-asyncapi/components/ParseErrors/ParseErrors.jsx
- src/plugins/editor-preview-asyncapi/index.js
- src/plugins/editor-preview-asyncapi/monaco.contribution.js
- src/plugins/editor-preview-asyncapi/reducers.js
- src/plugins/editor-preview-asyncapi/selectors.js
> feat(preview-asyncapi): project parser errors to editor markers

- src/plugins/layout/components/Layout/_layout.scss
> fix(layout): remove double-scrollbar in validation pane

- src/plugins/editor-monaco-language-apidom/language/apidom-mode.js
- src/plugins/editor-monaco-language-apidom/language/providers/CodeActionsProvider.js
- src/plugins/editor-monaco-language-apidom/language/providers/CompletionItemProvider.js
- src/plugins/editor-monaco-language-apidom/language/providers/DefinitionProvider.js
- src/plugins/editor-monaco-language-apidom/language/providers/DiagnosticsProvider.js
- src/plugins/editor-monaco-language-apidom/language/providers/DocumentLinkProvider.js
- src/plugins/editor-monaco-language-apidom/language/providers/DocumentSemanticTokensProvider.js
- src/plugins/editor-monaco-language-apidom/language/providers/DocumentSymbolProvider.js
- src/plugins/editor-monaco-language-apidom/language/providers/HoverProvider.js
- src/plugins/editor-monaco-language-apidom/language/providers/Provider.js
This regression was probably manifesting for quite some time.
> fix(monaco-language-apidom): fix regression in DocumentSymbolProvider

- src/plugins/editor-monaco/components/ValidationTable/_validation-table.scss
> fix(layout): allow scrolling within validation table

- Dockerfile
> fix(docker): update libtiff to non-vulnerable version

- src/plugins/editor-monaco-language-apidom/language/monaco.contribution.js
- src/plugins/editor-monaco-language-apidom/language/providers/DiagnosticsProvider.js
Error was caused by the wrong sequence of
initialization steps.
> fix(momnaco-language-apidom): fix VS Code API initialization error

- Dockerfile
This adds some metadata via [OCI annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md). 
This helps consumers understand better where the images are coming from.
Code inspection only.
> chore: add metadata annotations

- Dockerfile
- Dockerfile.unprivileged
> chore(docker): add metadata annotations

- src/plugins/editor-safe-render/index.js
The `EditorSafeRenderPlugin` can be utilized in any custom preset in following way:
```js
import SwaggerEditor from 'swagger-editor';
const preset = [
SwaggerEditor.plugins.EditorSafeRender,
];
```
By default the plugin wraps following components:
```
'TopBar',
'SwaggerEditorLayout',
'Editor',
'EditorTextarea',
'EditorMonaco',
'EditorPane',
'EditorPaneBarTop',
'EditorPreviewPane',
'ValidationPane',
'AlertDialog',
'ConfirmDialog',
'Dropzone',
```
If you don't use some of these components in your preset, don't worry, the plugin recognizes that and will ignore non-existing components.
---
If there is a need to append additional components to the plugin:
```js
import SwaggerEditor from 'swagger-editor';
const preset = [
SwaggerEditor.plugins.EditorSafeRender({ componentList: …
```
> feat(editor-save-render): configure plugin via options

- package-lock.json
- package.json
- src/plugins/editor-monaco/after-load.js
Refs https://github.com/CodinGame/monaco-vscode-api/issues/156
> chore(deps): update VSCode API to v1.80.3

- README.md
> docs(README): remove confusion around v4 and v5

- src/App.jsx
fixes #4493 
for OAS 2.0 and OAS 3.0
> enable showExtensions of OAS2.0/OAS3.0

- .eslintrc
- package-lock.json
- package.json
- src/plugins/editor-content-type/selectors.js
- src/plugins/editor-monaco-language-apidom/language/actions/dereference.js
- src/plugins/editor-preview-asyncapi/components/EditorPreviewAsyncAPI/EditorPreviewAsyncAPI.jsx
- src/plugins/top-bar/actions/convert-openapi-20-to-openapi-30x.js
- src/plugins/top-bar/actions/fetch-openapi2-generator-client-list.js
- src/plugins/top-bar/actions/fetch-openapi2-generator-server-list.js
- src/plugins/top-bar/actions/fetch-openapi3-generator-client-list.js
- src/plugins/top-bar/actions/fetch-openapi3-generator-server-list.js
- src/plugins/top-bar/actions/generate-client-code-from-openapi-20.js
- src/plugins/top-bar/actions/generate-client-code-from-openapi-3.js
- src/plugins/top-bar/actions/generate-server-code-from-openapi-20.js
- src/plugins/top-bar/actions/generate-server-code-from-openapi-3.js
- src/plugins/top-bar/actions/import-url.js
- src/plugins/top-bar/components/FileMenu/items/SaveAsMenuItem.jsx
> chore(deps-dev): bump prettier from 3.0.3 to 3.1.0

- package-lock.json
- package.json
- src/plugins/editor-preview-asyncapi/actions.js
This change adds support for parsing protocol buffers
by AsyncAPI parser.
> feat(editor-preview-asyncapi): add support for protobufs

- package-lock.json
- package.json
- src/plugins/editor-monaco/after-load.js
- src/plugins/editor-monaco/monaco-contribution/index.js
Refs https://github.com/CodinGame/monaco-vscode-api/issues/268
Refs https://github.com/CodinGame/monaco-vscode-api/issues/267
> fix(vscode): bring upstream VSCode fixes in

- package-lock.json
- package.json
> chore(deps-dev): bump @babel/plugin-transform-runtime to 7.23.7

- src/plugins/editor-content-fixtures/selectors/selectOpenAPI20PetstoreYAML.js
> fix(editor-content-fixtures): fix typo in OpenAPI 2.0

- src/plugins/json-schema-validator/validator/shared.js
- test/unit/plugins/validate-semantic/2and3/paths.js
- test/unit/standalone/topbar-insert/form-validation.js
> chore: Fix multiple typos

- .github/dependabot.yml
- package-lock.json
- package.json
> fix: use @asyncapi/react-component@1.0.0-next.48

- package-lock.json
- package.json
- test/cypress/e2e/plugin.editor-persistence.cy.js
> perf(language-apidom): improve performance of reference validation

- src/plugins/editor-preview-asyncapi/actions.js
> refactor(editor-preview-asyncapi): allow flexible options usage

- src/plugins/editor-content-fixtures/index.js
- src/plugins/editor-content-fixtures/selectors/selectAsyncAPI300PetstoreYAML.js
- src/plugins/top-bar/components/FileMenu/items/LoadExampleNestedMenu/LoadExampleNestedMenu.jsx
- src/plugins/top-bar/components/FileMenu/items/LoadExampleNestedMenu/LoadExampleNestedMenuHandler.jsx
- src/plugins/top-bar/components/FileMenu/items/LoadExampleNestedMenu/items/AsyncAPI30PetstoreMenuItem.jsx
- src/plugins/top-bar/index.js
> feat(top-bar): add support for loading AsyncAPI Petstore 3.0.0 example

- .husky/commit-msg
- .husky/pre-commit
- package-lock.json
- package.json
> chore(deps-dev): bump husky from 8.0.3 to 9.0.11

- src/plugins/editor-monaco/components/MonacoEditor/MonacoEditor.jsx
> fix(monaco-editor): avoid rendering Monaco Editor multiple times

- package-lock.json
- package.json
- src/App.jsx
> feat: integrate with new SwaggerUI config capabilities

- src/plugins/editor-content-read-only/wrap-components/EditorWrapper.jsx
> fix(content-read-only): priorize explicit prop over redux state

- README.md
> docs(README): fix v5 installation instructions

- src/plugins/editor-preview-asyncapi/components/AsyncAPIReactComponent.jsx
- src/plugins/editor-preview-asyncapi/components/EditorPreviewAsyncAPI/EditorPreviewAsyncAPI.jsx
- src/plugins/editor-preview-asyncapi/index.js
> feat(editor-preview-asyncapi): allow passing additional config

- .eslintrc
- package-lock.json
- package.json
> chore(deps): bump monaco-marker-data-provider from 1.1.1 to 1.2.2

- package-lock.json
- package.json
> chore(deps): bump swagger-ui from 5.13.0 to 5.17.5

- .github/workflows/codeql.yml
> ci: enable advanced CodeQL SAST analysis

- package-lock.json
- package.json
- swagger-editor-dist-package/package.json
Refs https://github.com/swagger-api/swagger-ui/issues/10197
> fix: update Scarf.js to v1.4.0 to avoid breaking Vitest

- src/plugins/editor-content-fixtures/index.js
- src/plugins/editor-content-fixtures/selectors/selectOpenAPI304PetstoreYAML.js
- src/plugins/editor-content-fixtures/selectors/selectOpenAPI311PetstoreYAML.js
- src/plugins/top-bar/components/FileMenu/items/LoadExampleNestedMenu/LoadExampleNestedMenuHandler.jsx
Supersedes https://github.com/swagger-api/swagger-editor/pull/5387
> fix(editor-content-fixtures): update Petstore to match SmartBear rules
